/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/home/kang/.asdf/installs/nim/2.2.4/lib -I/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament -o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@sstd@ssyncio.nim.c.o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@sstd@ssyncio.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <string.h>
#include <errno.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q;
typedef struct tyObject_CatchableError__XSmkP4BP1xjV2WPLkyayWQ tyObject_CatchableError__XSmkP4BP1xjV2WPLkyayWQ;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__3WRifCsYTwzEBSJeq60tSA tySequence__3WRifCsYTwzEBSJeq60tSA;
typedef struct tySequence__3WRifCsYTwzEBSJeq60tSA_Content tySequence__3WRifCsYTwzEBSJeq60tSA_Content;
typedef struct tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ;
typedef struct tyObject_StackTraceEntry__t37EfNpnik821mfIeIkUuQ tyObject_StackTraceEntry__t37EfNpnik821mfIeIkUuQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_FileMode__5xEO6tKrUv0N6TNNETBo0w;
typedef NCSTRING tyArray__0E7DNqei82BvXkf8SIJzgQ[5];
typedef NIM_CHAR tyArray__PbS9a6gkxCuxWEnFq4lOU9aw[24];
typedef NIM_CHAR tyArray__hToc9cajraNwyrQdTvLCS3A[116];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__3WRifCsYTwzEBSJeq60tSA {
  NI len; tySequence__3WRifCsYTwzEBSJeq60tSA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__3WRifCsYTwzEBSJeq60tSA trace;
	Exception* up;
};
struct tyObject_CatchableError__XSmkP4BP1xjV2WPLkyayWQ {
	Exception Sup;
};
struct tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q {
	tyObject_CatchableError__XSmkP4BP1xjV2WPLkyayWQ Sup;
};
typedef NU8 tyEnum_FileSeekPos__UlnZsjUsUkapwK2rt2ud1w;
struct tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ {
	tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q Sup;
};
struct tyObject_StackTraceEntry__t37EfNpnik821mfIeIkUuQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__3WRifCsYTwzEBSJeq60tSA_Content { NI cap; tyObject_StackTraceEntry__t37EfNpnik821mfIeIkUuQ data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open__stdZsyncio_u414)(FILE** f_p0, NimStringV2 filename_p1, tyEnum_FileMode__5xEO6tKrUv0N6TNNETBo0w mode_p2, NI bufSize_p3);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(int, getFileHandle__stdZsyncio_u279)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, modeIsDir__stdZsyncio_u408)(mode_t m_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2459)(NimStringV2* s_p0);
static N_INLINE(NIM_BOOL, eqeq___system_u8924)(NCSTRING x_p0, NCSTRING y_p1);
N_LIB_PRIVATE N_NIMCALL(void, checkErr__stdZsyncio_u162)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u29)(NI32 xX60gensym3__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseEIO__stdZsyncio_u92)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2711)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine__stdZsyncio_u289)(FILE* f_p0, NimStringV2* line_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseEOF__stdZsyncio_u95)(void);
N_LIB_PRIVATE N_NIMCALL(NI, writeBuffer__stdZsyncio_u196)(FILE* f_p0, void* buffer_p1, NI len_p2);
N_LIB_PRIVATE N_NIMCALL(NI, readBuffer__stdZsyncio_u165)(FILE* f_p0, void* buffer_p1, NI len_p2);
extern TNimTypeV2 NTIv2__tGpFWXHGj1lkAxgL9aiCc8Q_;
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2 = { 13 | NIM_STRLIT_FLAG, "cannot open: " };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_3 = {13, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_7 = { 7 | NIM_STRLIT_FLAG, "errno: " };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_8 = {7, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_7};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_9 = { 2 | NIM_STRLIT_FLAG, " `" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_10 = {2, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_9};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11 = { 1 | NIM_STRLIT_FLAG, "`" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_12 = {1, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_24 = { 24 | NIM_STRLIT_FLAG, "cannot set file position" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_25 = {24, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_24};
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_26 = { 29 | NIM_STRLIT_FLAG, "cannot retrieve file position" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_27 = {29, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_26};
extern TNimTypeV2 NTIv2__b2h2jKXr8miUYhz9bgvCZaQ_;
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_28 = { 11 | NIM_STRLIT_FLAG, "EOF reached" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_29 = {11, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_28};
static const struct {
  NI cap; NIM_CHAR data[27+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_30 = { 27 | NIM_STRLIT_FLAG, "cannot write string to file" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_31 = {27, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_30};
N_LIB_PRIVATE NIM_CONST tyArray__0E7DNqei82BvXkf8SIJzgQ FormatOpen__stdZsyncio_u402 = {"rbe",
"wbe",
"w+be",
"r+be",
"abe"}
;
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, setStdIoUnbuffered__stdZsyncio_u528)(void) {
	int T1_;
	int T2_;
	int T3_;
	nimfr_("setStdIoUnbuffered", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");
	nimlf_(812, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");	T1_ = (int)0;
	T1_ = setvbuf(stdout, NIM_NIL, _IONBF, ((size_t)0));
	(void)(T1_);
	nimln_(814);	T2_ = (int)0;
	T2_ = setvbuf(stderr, NIM_NIL, _IONBF, ((size_t)0));
	(void)(T2_);
	nimln_(816);	T3_ = (int)0;
	T3_ = setvbuf(stdin, NIM_NIL, _IONBF, ((size_t)0));
	(void)(T3_);
	popFrame();
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, getFileHandle__stdZsyncio_u279)(FILE* f_p0) {
	int result;
	nimfr_("getFileHandle", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");
	nimln_(359);	nimln_(364);	result = fileno(f_p0);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, modeIsDir__stdZsyncio_u408)(mode_t m_p0) {
	NIM_BOOL result;
	nimfr_("modeIsDir", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");
	nimln_(691);	nimln_(692);	result = ((NI32)(m_p0 & ((NI32)61440)) == ((NI32)16384));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open__stdZsyncio_u414)(FILE** f_p0, NimStringV2 filename_p1, tyEnum_FileMode__5xEO6tKrUv0N6TNNETBo0w mode_p2, NI bufSize_p3) {
	NIM_BOOL result;
	void* p_1;
NIM_BOOL* nimErr_;
	nimfr_("open", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	nimln_(718);	p_1 = fopen(nimToCStringConv(filename_p1), FormatOpen__stdZsyncio_u402[(mode_p2)- 0]);
	nimln_(719);	{
		FILE* f2_1;
		struct stat res_1;
		if (!!((p_1 == NIM_NIL))) goto LA3_;
		nimln_(720);		f2_1 = ((FILE*) (p_1));
		nimln_(726);		{
			NIM_BOOL T7_;
			int T8_;
			int T9_;
			T7_ = (NIM_BOOL)0;
			T8_ = (int)0;
			T8_ = getFileHandle__stdZsyncio_u279(f2_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T9_ = (int)0;
			T9_ = fstat(T8_, (&res_1));
			T7_ = (((NI32)0) <= T9_);
			if (!(T7_)) goto LA10_;
			T7_ = modeIsDir__stdZsyncio_u408(res_1.st_mode);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
LA10_: ;
			if (!T7_) goto LA11_;
			nimln_(727);			{
				int T17_;
				nimln_(327);				if (!!((f2_1 == 0))) goto LA15_;
				nimln_(328);				T17_ = (int)0;
				T17_ = fclose(f2_1);
				(void)(T17_);
			}
LA15_: ;
			nimln_(728);			nimln_(709);			nimln_(728);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA11_: ;
		nimln_(735);		result = NIM_TRUE;
		nimln_(736);		(*f_p0) = ((FILE*) (p_1));
		nimln_(737);		{
			NIM_BOOL T20_;
			int T24_;
			T20_ = (NIM_BOOL)0;
			T20_ = (((NI)0) < bufSize_p3);
			if (!(T20_)) goto LA21_;
			T20_ = ((NU64)(((NU) (bufSize_p3))) <= (NU64)(((NU)-1)));
LA21_: ;
			if (!T20_) goto LA22_;
			nimln_(738);			T24_ = (int)0;
			T24_ = setvbuf((*f_p0), NIM_NIL, _IOFBF, ((size_t) (bufSize_p3)));
			(void)(T24_);
		}
		goto LA18_;
LA22_: ;
		{
			int T28_;
			nimln_(739);			if (!(bufSize_p3 == ((NI)0))) goto LA26_;
			nimln_(740);			T28_ = (int)0;
			T28_ = setvbuf((*f_p0), NIM_NIL, _IONBF, ((size_t)0));
			(void)(T28_);
		}
		goto LA18_;
LA26_: ;
LA18_: ;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(742);		result = NIM_FALSE;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(FILE*, open__stdZsyncio_u487)(NimStringV2 filename_p0, tyEnum_FileMode__5xEO6tKrUv0N6TNNETBo0w mode_p1, NI bufSize_p2) {
	FILE* result;
NIM_BOOL* nimErr_;
	nimfr_("open", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	nimln_(786);	result = 0;
	nimln_(787);	{
		NIM_BOOL T3_;
		tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q* T6_;
		NimStringV2 T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = open__stdZsyncio_u414(&result, filename_p0, mode_p1, bufSize_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T3_)) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q*) nimNewObj(sizeof(tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q), NIM_ALIGNOF(tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__tGpFWXHGj1lkAxgL9aiCc8Q_);
		(*T6_).Sup.Sup.name = "IOError";
		nimln_(788);		T7_.len = 0; T7_.p = NIM_NIL;
		T7_ = rawNewString(filename_p0.len + 13);
appendString((&T7_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_3);
appendString((&T7_), filename_p0);
		(*T6_).Sup.Sup.message = T7_;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T6_, "IOError", "open", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim", 788);
goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2459(s_p0);
	}
LA5_: ;
}
static N_INLINE(NIM_BOOL, eqeq___system_u8924)(NCSTRING x_p0, NCSTRING y_p1) {
	NIM_BOOL result;
	nimfr_("==", "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");
	nimlf_(2729, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");	{
		if (!(((void*) (x_p0)) == ((void*) (y_p1)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T6_;
		nimln_(2730);		T6_ = (NIM_BOOL)0;
		T6_ = (((void*) (x_p0)) == NIM_NIL);
		if (T6_) goto LA7_;
		T6_ = (((void*) (y_p1)) == NIM_NIL);
LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
LA8_: ;
	{
		int T11_;
		nimln_(2731);		T11_ = (int)0;
		T11_ = strcmp(x_p0, y_p1);
		result = (T11_ == ((NI32)0));
	}
LA1_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseEIO__stdZsyncio_u92)(NimStringV2 msg_p0) {
	NimStringV2 colontmpD_;
	tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q* T1_;
	nimfr_("raiseEIO", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");
{	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q*) nimNewObj(sizeof(tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q), NIM_ALIGNOF(tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__tGpFWXHGj1lkAxgL9aiCc8Q_);
	(*T1_).Sup.Sup.name = "IOError";
	nimlf_(157, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");	nimlf_(1694, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");	colontmpD_ = eqdup___system_u2711(msg_p0);
	(*T1_).Sup.Sup.message = colontmpD_;
	(*T1_).Sup.Sup.parent = ((Exception*) NIM_NIL);
	nimlf_(157, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");	raiseExceptionEx((Exception*)T1_, "IOError", "raiseEIO", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim", 157);
goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, checkErr__stdZsyncio_u162)(FILE* f_p0) {
NIM_BOOL* nimErr_;
	nimfr_("checkErr", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	nimln_(171);	{
		int T3_;
		NimStringV2 msg_1;
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		NimStringV2 T7_;
		NCSTRING T8_;
		T3_ = (int)0;
		T3_ = ferror(f_p0);
		if (!!((T3_ == ((NI32)0)))) goto LA4_;
		msg_1.len = 0; msg_1.p = NIM_NIL;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimln_(172);		T7_.len = 0; T7_.p = NIM_NIL;
		colontmpD_ = dollar___systemZdollars_u29(errno);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		T8_ = (NCSTRING)0;
		T8_ = strerror(errno);
		colontmpD__2 = cstrToNimstr(T8_);
		T7_ = rawNewString(colontmpD_.len + colontmpD__2.len + 10);
appendString((&T7_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_8);
appendString((&T7_), colontmpD_);
appendString((&T7_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_10);
appendString((&T7_), colontmpD__2);
appendString((&T7_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_12);
		msg_1 = T7_;
		nimln_(173);		clearerr(f_p0);
		nimln_(174);		raiseEIO__stdZsyncio_u92(msg_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		{
			LA6_:;
		}
		{
			nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			if (msg_1.p && !(msg_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(msg_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine__stdZsyncio_u289)(FILE* f_p0, NimStringV2* line_p1) {
	NIM_BOOL result;
	NI pos_1;
	NI sp_1;
NIM_BOOL* nimErr_;
	nimfr_("readLine", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(404, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");	result = NIM_FALSE;
	nimln_(468);	pos_1 = ((NI)0);
	nimln_(471);	sp_1 = (((*line_p1).len >= ((NI)80)) ? (*line_p1).len : ((NI)80));
	nimln_(472);	if ((sp_1) < ((NI)0) || (sp_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(sp_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	setLengthStrV2((&(*line_p1)), (sp_1));
	{
		nimln_(474);		while (1) {
			NIM_BOOL fgetsSuccess_1;
			void* m_1;
			NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_22;
			NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_23;
			{
				NI i_1;
				NI i_2;
				i_1 = (NI)0;
				nimlf_(128, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators_1.nim");				i_2 = ((NI)0);
				{
					nimln_(129);					while (1) {
						NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5;
						NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_6;
						if (!(i_2 < sp_1)) goto LA5;
						nimlf_(477, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");						i_1 = i_2;
						if (nimAddInt(pos_1, i_1, &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5) < 0 || (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5) >= (*line_p1).len){ raiseIndexError2((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5),(*line_p1).len-1); goto BeforeRet_;
						}
						nimPrepareStrMutationV2((&(*line_p1)));
						(*line_p1).p->data[(NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5)] = 10;
						nimlf_(131, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators_1.nim");						if (nimAddInt(i_2, ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_6)) { raiseOverflow(); goto BeforeRet_;
						};
						i_2 = (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_6);
					} LA5: ;
				}
			}
			fgetsSuccess_1 = (NIM_BOOL)0;
			{
				nimlf_(480, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");				while (1) {
					{
						NCSTRING T9_;
						NIM_BOOL T10_;
						nimln_(483);						if (pos_1 < 0 || pos_1 >= (*line_p1).len){ raiseIndexError2(pos_1,(*line_p1).len-1); goto BeforeRet_;
						}
						if ((sp_1) < ((int)(-2147483647 -1)) || (sp_1) > ((int)2147483647)){ raiseRangeErrorI(sp_1, ((int)(-2147483647 -1)), ((int)2147483647)); goto BeforeRet_;
						}
						T9_ = (NCSTRING)0;
						T9_ = fgets(((NCSTRING) ((&(*line_p1).p->data[pos_1]))), ((int) (sp_1)), f_p0);
						T10_ = (NIM_BOOL)0;
						T10_ = eqeq___system_u8924(T9_, ((NCSTRING) NIM_NIL));
						fgetsSuccess_1 = !(T10_);
						nimln_(484);						{
							if (!fgetsSuccess_1) goto LA13_;
							goto LA6;
						}
LA13_: ;
						nimln_(486);						{
							if (!(errno == EINTR)) goto LA17_;
							nimln_(487);							errno = ((int)0);
							nimln_(488);							clearerr(f_p0);
							nimln_(489);							goto LA8;
						}
LA17_: ;
						nimln_(490);						checkErr__stdZsyncio_u162(f_p0);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						nimln_(491);						goto LA6;
					} LA8: ;
				}
			} LA6: ;
			nimln_(493);			if (pos_1 < 0 || pos_1 >= (*line_p1).len){ raiseIndexError2(pos_1,(*line_p1).len-1); goto BeforeRet_;
			}
			m_1 = memchr(((void*) ((&(*line_p1).p->data[pos_1]))), ((int)10), ((size_t) (sp_1)));
			nimln_(494);			{
				NI last_1;
				NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_13;
				NIM_BOOL T42_;
				if (!!((m_1 == NIM_NIL))) goto LA21_;
				nimln_(496);				if (((NI)0) < 0 || ((NI)0) >= (*line_p1).len){ raiseIndexError2(((NI)0),(*line_p1).len-1); goto BeforeRet_;
				}
				if (nimSubInt(((NI) (ptrdiff_t) (m_1)), ((NI) (ptrdiff_t) ((&(*line_p1).p->data[((NI)0)]))), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_13)) { raiseOverflow(); goto BeforeRet_;
				};
				last_1 = (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_13);
				nimln_(497);				{
					NIM_BOOL T25_;
					NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_14;
					NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_15;
					NIM_BOOL T29_;
					T25_ = (NIM_BOOL)0;
					T25_ = (((NI)0) < last_1);
					if (!(T25_)) goto LA26_;
					if (nimSubInt(last_1, ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_14)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_14) < 0 || (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_14) >= (*line_p1).len){ raiseIndexError2((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_14),(*line_p1).len-1); goto BeforeRet_;
					}
					T25_ = ((NU8)((*line_p1).p->data[(NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_14)]) == (NU8)(13));
LA26_: ;
					if (!T25_) goto LA27_;
					nimln_(498);					if (nimSubInt(last_1, ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_15)) { raiseOverflow(); goto BeforeRet_;
					};
					if (((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_15)) < ((NI)0) || ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_15)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_15), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
					}
					setLengthStrV2((&(*line_p1)), ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_15)));
					nimln_(499);					nimln_(396);					nimln_(499);					T29_ = (NIM_BOOL)0;
					T29_ = (((NI)1) < last_1);
					if (T29_) goto LA30_;
					T29_ = fgetsSuccess_1;
LA30_: ;
					result = T29_;
					goto BeforeRet_;
				}
				goto LA23_;
LA27_: ;
				{
					NIM_BOOL T32_;
					NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_16;
					nimln_(500);					T32_ = (NIM_BOOL)0;
					T32_ = (((NI)0) < last_1);
					if (!(T32_)) goto LA33_;
					if (nimSubInt(last_1, ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_16)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_16) < 0 || (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_16) >= (*line_p1).len){ raiseIndexError2((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_16),(*line_p1).len-1); goto BeforeRet_;
					}
					T32_ = ((NU8)((*line_p1).p->data[(NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_16)]) == (NU8)(0));
LA33_: ;
					if (!T32_) goto LA34_;
					nimln_(505);					{
						NIM_BOOL T38_;
						NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_17;
						NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_18;
						NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_19;
						NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_20;
						T38_ = (NIM_BOOL)0;
						if (nimAddInt(pos_1, sp_1, &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_17)) { raiseOverflow(); goto BeforeRet_;
						};
						if (nimSubInt((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_17), ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_18)) { raiseOverflow(); goto BeforeRet_;
						};
						T38_ = ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_18) <= last_1);
						if (T38_) goto LA39_;
						if (nimAddInt(last_1, ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_19)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_19) < 0 || (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_19) >= (*line_p1).len){ raiseIndexError2((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_19),(*line_p1).len-1); goto BeforeRet_;
						}
						T38_ = !(((NU8)((*line_p1).p->data[(NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_19)]) == (NU8)(0)));
LA39_: ;
						if (!T38_) goto LA40_;
						nimln_(506);						if (nimSubInt(last_1, ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_20)) { raiseOverflow(); goto BeforeRet_;
						};
						last_1 = (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_20);
					}
LA40_: ;
				}
				goto LA23_;
LA34_: ;
LA23_: ;
				nimln_(507);				if ((last_1) < ((NI)0) || (last_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(last_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				setLengthStrV2((&(*line_p1)), (last_1));
				nimln_(508);				nimln_(396);				nimln_(508);				T42_ = (NIM_BOOL)0;
				T42_ = (((NI)0) < last_1);
				if (T42_) goto LA43_;
				T42_ = fgetsSuccess_1;
LA43_: ;
				result = T42_;
				goto BeforeRet_;
			}
			goto LA19_;
LA21_: ;
			{
				NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_21;
				nimln_(511);				if (nimSubInt(sp_1, ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_21)) { raiseOverflow(); goto BeforeRet_;
				};
				sp_1 = (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_21);
			}
LA19_: ;
			nimln_(513);			if (nimAddInt(pos_1, sp_1, &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_22)) { raiseOverflow(); goto BeforeRet_;
			};
			pos_1 = (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_22);
			nimln_(514);			sp_1 = ((NI)128);
			nimln_(515);			if (nimAddInt(pos_1, sp_1, &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_23)) { raiseOverflow(); goto BeforeRet_;
			};
			if (((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_23)) < ((NI)0) || ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_23)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_23), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			setLengthStrV2((&(*line_p1)), ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_23)));
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setFilePos__stdZsyncio_u498)(FILE* f_p0, NI64 pos_p1, tyEnum_FileSeekPos__UlnZsjUsUkapwK2rt2ud1w relativeTo_p2) {
NIM_BOOL* nimErr_;
	nimfr_("setFilePos", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	nimln_(793);	{
		int T3_;
		T3_ = (int)0;
		T3_ = fseeko(f_p0, pos_p1, ((int) (relativeTo_p2)));
		if (!!((T3_ == ((NI32)0)))) goto LA4_;
		nimln_(794);		raiseEIO__stdZsyncio_u92(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_25);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI64, getFilePos__stdZsyncio_u521)(FILE* f_p0) {
	NI64 result;
NIM_BOOL* nimErr_;
	nimfr_("getFilePos", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	nimln_(799);	result = ftello(f_p0);
	nimln_(800);	{
		if (!(result < IL64(0))) goto LA3_;
		raiseEIO__stdZsyncio_u92(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_27);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseEOF__stdZsyncio_u95)(void) {
	tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ* T1_;
	nimfr_("raiseEOF", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");
{	T1_ = NIM_NIL;
	T1_ = (tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ*) nimNewObj(sizeof(tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ), NIM_ALIGNOF(tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ));
	(*T1_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__b2h2jKXr8miUYhz9bgvCZaQ_);
	(*T1_).Sup.Sup.Sup.name = "EOFError";
	(*T1_).Sup.Sup.Sup.message = TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_29;
	(*T1_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
	nimln_(160);	raiseExceptionEx((Exception*)T1_, "EOFError", "raiseEOF", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim", 160);
goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readLine__stdZsyncio_u318)(FILE* f_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("readLine", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	nimln_(521);	result = rawNewString(((NI)80));
	nimln_(522);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = readLine__stdZsyncio_u289(f_p0, (&result));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T3_)) goto LA4_;
		raiseEOF__stdZsyncio_u95();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, writeBuffer__stdZsyncio_u196)(FILE* f_p0, void* buffer_p1, NI len_p2) {
	NI result;
	size_t T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (size_t)0;
	T1_ = fwrite(buffer_p1, ((size_t)1), ((size_t) (len_p2)), f_p0);
	result = ((NI) (T1_));
	checkErr__stdZsyncio_u162(f_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_u254)(FILE* f_p0, NimStringV2 s_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI T3_;
		if ((s_p1.len) < ((NI)0) || (s_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		T3_ = (NI)0;
		T3_ = writeBuffer__stdZsyncio_u196(f_p0, ((void*) (nimToCStringConv(s_p1))), (s_p1.len));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!((T3_ == s_p1.len))) goto LA4_;
		raiseEIO__stdZsyncio_u92(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_31);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u268)(FILE* f_p0) {
	nimfr_("close", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");
	nimln_(343);	{
		int T5_;
		nimln_(327);		if (!!((f_p0 == 0))) goto LA3_;
		nimln_(328);		T5_ = (int)0;
		T5_ = fclose(f_p0);
		(void)(T5_);
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI, readBuffer__stdZsyncio_u165)(FILE* f_p0, void* buffer_p1, NI len_p2) {
	NI result;
	size_t T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (size_t)0;
	T1_ = fread(buffer_p1, ((size_t)1), ((size_t) (len_p2)), f_p0);
	result = ((NI) (T1_));
	{
		if (!!((result == len_p2))) goto LA4_;
		checkErr__stdZsyncio_u162(f_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, readChars__stdZsyncio_u177)(FILE* f_p0, NIM_CHAR* a_p1, NI a_p1Len_0) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	if (((NI)0) < 0 || ((NI)0) >= a_p1Len_0){ raiseIndexError2(((NI)0),a_p1Len_0-1); goto BeforeRet_;
	}
	if ((a_p1Len_0) < ((NI)0) || (a_p1Len_0) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(a_p1Len_0, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = readBuffer__stdZsyncio_u165(f_p0, ((void*) ((&a_p1[((NI)0)]))), (a_p1Len_0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
