/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/home/kang/.asdf/installs/nim/2.2.4/lib -I/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament -o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@ssystem@sexceptions.nim.c.o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@ssystem@sexceptions.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_OverflowDefect__he9cszpIcHpfu2fAxj5HN8A tyObject_OverflowDefect__he9cszpIcHpfu2fAxj5HN8A;
typedef struct tyObject_RefHeader__ePn9aaKjYGVaTHdO19bZU4aw tyObject_RefHeader__ePn9aaKjYGVaTHdO19bZU4aw;
typedef struct tyObject_ArithmeticDefect__u66C2MSGeBgotzisG1lb1A tyObject_ArithmeticDefect__u66C2MSGeBgotzisG1lb1A;
typedef struct tyObject_Defect__9cO87tuy1qb5CAJEr5a5Gsw tyObject_Defect__9cO87tuy1qb5CAJEr5a5Gsw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__3WRifCsYTwzEBSJeq60tSA tySequence__3WRifCsYTwzEBSJeq60tSA;
typedef struct tySequence__3WRifCsYTwzEBSJeq60tSA_Content tySequence__3WRifCsYTwzEBSJeq60tSA_Content;
typedef struct tyObject_GcEnv__9aFpsR2FYaWcUth4It0SlFw tyObject_GcEnv__9aFpsR2FYaWcUth4It0SlFw;
typedef struct tyObject_CellSeq__rtBKeZXpk8LfroV04nwLcQ tyObject_CellSeq__rtBKeZXpk8LfroV04nwLcQ;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__du6HnYB7FwfCF5rdSoiVAQ tyObject_CellSeq__du6HnYB7FwfCF5rdSoiVAQ;
typedef struct tyTuple__i9a57FIZC1dU31UhzkAjNNw tyTuple__i9a57FIZC1dU31UhzkAjNNw;
typedef struct tyObject_RangeDefect__khCKR7boxcvnFyR4kDu1KQ tyObject_RangeDefect__khCKR7boxcvnFyR4kDu1KQ;
typedef struct tyObject_IndexDefect__IdHlr9bKED9b1LW6Cb4TxLQA tyObject_IndexDefect__IdHlr9bKED9b1LW6Cb4TxLQA;
typedef struct tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q;
typedef struct tyObject_CatchableError__XSmkP4BP1xjV2WPLkyayWQ tyObject_CatchableError__XSmkP4BP1xjV2WPLkyayWQ;
typedef struct tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ;
typedef struct tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg;
typedef struct tyObject_StackTraceEntry__t37EfNpnik821mfIeIkUuQ tyObject_StackTraceEntry__t37EfNpnik821mfIeIkUuQ;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__ePn9aaKjYGVaTHdO19bZU4aw {
	NI rc;
	NI rootIdx;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__3WRifCsYTwzEBSJeq60tSA {
  NI len; tySequence__3WRifCsYTwzEBSJeq60tSA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__3WRifCsYTwzEBSJeq60tSA trace;
	Exception* up;
};
struct tyObject_Defect__9cO87tuy1qb5CAJEr5a5Gsw {
	Exception Sup;
};
struct tyObject_ArithmeticDefect__u66C2MSGeBgotzisG1lb1A {
	tyObject_Defect__9cO87tuy1qb5CAJEr5a5Gsw Sup;
};
struct tyObject_OverflowDefect__he9cszpIcHpfu2fAxj5HN8A {
	tyObject_ArithmeticDefect__u66C2MSGeBgotzisG1lb1A Sup;
};
struct tyObject_CellSeq__rtBKeZXpk8LfroV04nwLcQ {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__du6HnYB7FwfCF5rdSoiVAQ {
	NI len;
	NI cap;
	tyTuple__i9a57FIZC1dU31UhzkAjNNw* d;
};
struct tyObject_GcEnv__9aFpsR2FYaWcUth4It0SlFw {
	tyObject_CellSeq__rtBKeZXpk8LfroV04nwLcQ traceStack;
	tyObject_CellSeq__du6HnYB7FwfCF5rdSoiVAQ toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyObject_RangeDefect__khCKR7boxcvnFyR4kDu1KQ {
	tyObject_Defect__9cO87tuy1qb5CAJEr5a5Gsw Sup;
};
struct tyObject_IndexDefect__IdHlr9bKED9b1LW6Cb4TxLQA {
	tyObject_Defect__9cO87tuy1qb5CAJEr5a5Gsw Sup;
};
struct tyObject_CatchableError__XSmkP4BP1xjV2WPLkyayWQ {
	Exception Sup;
};
struct tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q {
	tyObject_CatchableError__XSmkP4BP1xjV2WPLkyayWQ Sup;
};
struct tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ {
	tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q Sup;
};
struct tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg {
	tyObject_Defect__9cO87tuy1qb5CAJEr5a5Gsw Sup;
};
struct tyObject_StackTraceEntry__t37EfNpnik821mfIeIkUuQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__3WRifCsYTwzEBSJeq60tSA_Content { NI cap; tyObject_StackTraceEntry__t37EfNpnik821mfIeIkUuQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5266)(tyObject_OverflowDefect__he9cszpIcHpfu2fAxj5HN8A* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3546)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__ePn9aaKjYGVaTHdO19bZU4aw* s_p1, TNimTypeV2* desc_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u74)(tySequence__3WRifCsYTwzEBSJeq60tSA dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5278)(tyObject_OverflowDefect__he9cszpIcHpfu2fAxj5HN8A* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3029)(tyObject_CellSeq__rtBKeZXpk8LfroV04nwLcQ* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3037)(tyObject_CellSeq__rtBKeZXpk8LfroV04nwLcQ* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u60)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4793)(tyObject_RangeDefect__khCKR7boxcvnFyR4kDu1KQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4805)(tyObject_RangeDefect__khCKR7boxcvnFyR4kDu1KQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4862)(tyObject_IndexDefect__IdHlr9bKED9b1LW6Cb4TxLQA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4874)(tyObject_IndexDefect__IdHlr9bKED9b1LW6Cb4TxLQA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u9033)(tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u9045)(tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZsyncio_u100)(tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZsyncio_u112)(tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u68)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u35)(tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZassertions_u47)(tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg* dest_p0, void* env_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__he9cszpIcHpfu2fAxj5HN8A_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__khCKR7boxcvnFyR4kDu1KQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__IdHlr9bKED9b1LW6Cb4TxLQA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__tGpFWXHGj1lkAxgL9aiCc8Q_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__b2h2jKXr8miUYhz9bgvCZaQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__Xsk2vic9cj3cCxGsAlPPSXg_;
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[5] = {3701606400, 1285336064, 4013667840, 2927810560, 4025273856};
N_LIB_PRIVATE TNimTypeV2 NTIv2__he9cszpIcHpfu2fAxj5HN8A_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u56, .size = sizeof(tyObject_OverflowDefect__he9cszpIcHpfu2fAxj5HN8A), .align = (NI16) NIM_ALIGNOF(tyObject_OverflowDefect__he9cszpIcHpfu2fAxj5HN8A), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_3, .traceImpl = (void*)eqtrace___system_u5278, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_5[4] = {3701606400, 1285336064, 4013667840, 277497600};
N_LIB_PRIVATE TNimTypeV2 NTIv2__khCKR7boxcvnFyR4kDu1KQ_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u60, .size = sizeof(tyObject_RangeDefect__khCKR7boxcvnFyR4kDu1KQ), .align = (NI16) NIM_ALIGNOF(tyObject_RangeDefect__khCKR7boxcvnFyR4kDu1KQ), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_5, .traceImpl = (void*)eqtrace___system_u4805, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_6[4] = {3701606400, 1285336064, 4013667840, 3521490688};
N_LIB_PRIVATE TNimTypeV2 NTIv2__IdHlr9bKED9b1LW6Cb4TxLQA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u62, .size = sizeof(tyObject_IndexDefect__IdHlr9bKED9b1LW6Cb4TxLQA), .align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__IdHlr9bKED9b1LW6Cb4TxLQA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_6, .traceImpl = (void*)eqtrace___system_u4874, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_7[4] = {3701606400, 1285336064, 698629888, 1782929664};
N_LIB_PRIVATE TNimTypeV2 NTIv2__tGpFWXHGj1lkAxgL9aiCc8Q_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u64, .size = sizeof(tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q), .align = (NI16) NIM_ALIGNOF(tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_7, .traceImpl = (void*)eqtrace___system_u9045, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_8[5] = {3701606400, 1285336064, 698629888, 1782929664, 1752599552};
N_LIB_PRIVATE TNimTypeV2 NTIv2__b2h2jKXr8miUYhz9bgvCZaQ_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u66, .size = sizeof(tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ), .align = (NI16) NIM_ALIGNOF(tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_8, .traceImpl = (void*)eqtrace___stdZsyncio_u112, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_9[4] = {3701606400, 1285336064, 4013667840, 3375808000};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Xsk2vic9cj3cCxGsAlPPSXg_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u68, .size = sizeof(tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg), .align = (NI16) NIM_ALIGNOF(tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_9, .traceImpl = (void*)eqtrace___stdZassertions_u47, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/home/kang/.asdf/installs/nim/2.2.4/lib/system/arithmetics.nim");
	nimlf_(364, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("nimDecRefIsLastCyclicDyn", "/home/kang/.asdf/installs/nim/2.2.4/lib/system/orc.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(512, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(513);	{
		tyObject_RefHeader__ePn9aaKjYGVaTHdO19bZU4aw* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(514);		nimlf_(58, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__ePn9aaKjYGVaTHdO19bZU4aw*) (T5_));
		nimlf_(515, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(516);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			NI TM__TzI3paKQY09cLjc9cmCvur3A_2;
			nimln_(519);			if (nimSubInt((*cell_1).rc, ((NI)16), &TM__TzI3paKQY09cLjc9cmCvur3A_2)) { raiseOverflow(); goto BeforeRet_;
			};
			(*cell_1).rc = (NI)(TM__TzI3paKQY09cLjc9cmCvur3A_2);
		}
LA6_: ;
		nimln_(521);		rememberCycle__system_u3546(result, cell_1, (*((TNimTypeV2**) (p_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5266)(tyObject_OverflowDefect__he9cszpIcHpfu2fAxj5HN8A* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u5266(((tyObject_OverflowDefect__he9cszpIcHpfu2fAxj5HN8A*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, add__system_u3029)(tyObject_CellSeq__rtBKeZXpk8LfroV04nwLcQ* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	NI TM__TzI3paKQY09cLjc9cmCvur3A_4;
	nimfr_("add", "/home/kang/.asdf/installs/nim/2.2.4/lib/system/cellseqs_v2.nim");
{	nimlf_(28, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u3037(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	if (nimAddInt((*s_p0).len, ((NI)1), &TM__TzI3paKQY09cLjc9cmCvur3A_4)) { raiseOverflow(); goto BeforeRet_;
	};
	(*s_p0).len = (NI)(TM__TzI3paKQY09cLjc9cmCvur3A_4);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "/home/kang/.asdf/installs/nim/2.2.4/lib/system/orc.nim");
	nimlf_(136, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(137);	{
		tyObject_GcEnv__9aFpsR2FYaWcUth4It0SlFw* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(138);		j_1 = ((tyObject_GcEnv__9aFpsR2FYaWcUth4It0SlFw*) (env_p1));
		nimln_(139);		add__system_u3029((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5278)(tyObject_OverflowDefect__he9cszpIcHpfu2fAxj5HN8A* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4793)(tyObject_RangeDefect__khCKR7boxcvnFyR4kDu1KQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u60)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4793(((tyObject_RangeDefect__khCKR7boxcvnFyR4kDu1KQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4805)(tyObject_RangeDefect__khCKR7boxcvnFyR4kDu1KQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4862)(tyObject_IndexDefect__IdHlr9bKED9b1LW6Cb4TxLQA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4862(((tyObject_IndexDefect__IdHlr9bKED9b1LW6Cb4TxLQA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4874)(tyObject_IndexDefect__IdHlr9bKED9b1LW6Cb4TxLQA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u9033)(tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u9033(((tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u9045)(tyObject_IOError__tGpFWXHGj1lkAxgL9aiCc8Q* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZsyncio_u100)(tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___stdZsyncio_u100(((tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZsyncio_u112)(tyObject_EOFError__b2h2jKXr8miUYhz9bgvCZaQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u35)(tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u68)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___stdZassertions_u35(((tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZassertions_u47)(tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
