/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/home/kang/.asdf/installs/nim/2.2.4/lib -I/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament -o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@snimble@spkgs2@sballs-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29@sballs@sstyle.nim.c.o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@snimble@spkgs2@sballs-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29@sballs@sstyle.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <pthread.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef long tyArray__JnDexEsSwd1sgw7BR9b59bgw[5];
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isatty__pureZterminal_u625)(FILE* f_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, acquire__coreZrlocks_u35)(pthread_mutex_t* lock_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, writeLine__OOZOOZsrcZnutilsZfrontpatch_u14)(FILE* f_p0, NimStringV2* x_p1, NI x_p1Len_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_u254)(FILE* f_p0, NimStringV2 s_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuJoinSep)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 sep_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(void, release__coreZrlocks_u37)(pthread_mutex_t* lock_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__3wwPUfsm39bDy6fZH9bbTKVw_2 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__3wwPUfsm39bDy6fZH9bbTKVw_3 = {1, (NimStrPayload*)&TM__3wwPUfsm39bDy6fZH9bbTKVw_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__3wwPUfsm39bDy6fZH9bbTKVw_4 = { 1 | NIM_STRLIT_FLAG, " " };
static const NimStringV2 TM__3wwPUfsm39bDy6fZH9bbTKVw_5 = {1, (NimStrPayload*)&TM__3wwPUfsm39bDy6fZH9bbTKVw_4};
N_LIB_PRIVATE NIM_BOOL useColor__pkgZballsZstyle_u13;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
extern pthread_mutex_t clobber__pkgZballsZspec_u93;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
static N_INLINE(void, acquire__coreZrlocks_u35)(pthread_mutex_t* lock_p0) {
	nimfr_("acquire", "/home/kang/.asdf/installs/nim/2.2.4/lib/core/rlocks.nim");
	nimlf_(44, "/home/kang/.asdf/installs/nim/2.2.4/lib/core/rlocks.nim");	pthread_mutex_lock(lock_p0);
	popFrame();
}
static N_INLINE(void, writeLine__OOZOOZsrcZnutilsZfrontpatch_u14)(FILE* f_p0, NimStringV2* x_p1, NI x_p1Len_0) {
NIM_BOOL* nimErr_;
	nimfr_("writeLine", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	{
		NimStringV2* i_1;
		NI i_2;
		i_1 = (NimStringV2*)0;
		nimlf_(18, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators.nim");		i_2 = ((NI)0);
		{
			nimln_(19);			while (1) {
				if (!(i_2 < x_p1Len_0)) goto LA3;
				nimlf_(622, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");				if (i_2 < 0 || i_2 >= x_p1Len_0){ raiseIndexError2(i_2,x_p1Len_0-1); goto BeforeRet_;
				}
				i_1 = (&x_p1[i_2]);
				nimln_(623);				write__stdZsyncio_u254(f_p0, (*i_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(13, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators.nim");				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	nimlf_(624, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");	write__stdZsyncio_u254(f_p0, TM__3wwPUfsm39bDy6fZH9bbTKVw_3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, release__coreZrlocks_u37)(pthread_mutex_t* lock_p0) {
	nimfr_("release", "/home/kang/.asdf/installs/nim/2.2.4/lib/core/rlocks.nim");
	nimlf_(48, "/home/kang/.asdf/installs/nim/2.2.4/lib/core/rlocks.nim");	pthread_mutex_unlock(lock_p0);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, checkpoint__pkgZballsZstyle_u75)(NimStringV2* ss_p0, NI ss_p0Len_0) {
	NimStringV2 colontmpD_;
	tyArray__nHXaesL0DJZHyVS07ARPRA T3_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("checkpoint", "/home/kang/.asdf/installs/nim/2.2.4/nimble/pkgs2/balls-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29/balls/style.nim");
{nimErr_ = nimErrorFlag();
	nimln_(52);	acquire__coreZrlocks_u35((&clobber__pkgZballsZspec_u93));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(102, "/home/kang/.asdf/installs/nim/2.2.4/nimble/pkgs2/balls-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29/balls/style.nim");	colontmpD_ = nsuJoinSep(ss_p0, ss_p0Len_0, TM__3wwPUfsm39bDy6fZH9bbTKVw_5);
	if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
	T3_[0] = colontmpD_;
	writeLine__OOZOOZsrcZnutilsZfrontpatch_u14(stderr, T3_, 1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
	{
		LA2_:;
	}
	{
		nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimlf_(57, "/home/kang/.asdf/installs/nim/2.2.4/lib/core/rlocks.nim");		release__coreZrlocks_u37((&clobber__pkgZballsZspec_u93));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotasdfatsinstallsatsnimats2dot2dot4atsnimbleatspkgs2atsballsminus6dot0dot0minus795357f7959964fe9b50a47583d4aae239fa3d29atsballsatsstyledotnim_Init000)(void) {
{
	NIM_BOOL T1_;
NIM_BOOL* nimErr_;
	nimfr_("style", "/home/kang/.asdf/installs/nim/2.2.4/nimble/pkgs2/balls-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29/balls/style.nim");
nimErr_ = nimErrorFlag();
	nimlf_(32, "/home/kang/.asdf/installs/nim/2.2.4/nimble/pkgs2/balls-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29/balls/style.nim");	T1_ = (NIM_BOOL)0;
	T1_ = isatty__pureZterminal_u625(stderr);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	useColor__pkgZballsZstyle_u13 = T1_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

