/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/home/kang/.asdf/installs/nim/2.2.4/lib -I/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament -o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@snimble@spkgs2@sballs-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29@sballs@sspec.nim.c.o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@snimble@spkgs2@sballs-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29@sballs@sspec.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <string.h>
#include <pthread.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef long tyArray__JnDexEsSwd1sgw7BR9b59bgw[5];
typedef int tyArray__y9cEmKvKoWBNvZLJvncDPkg[1];
static N_INLINE(void, initRLock__coreZrlocks_u3)(pthread_mutex_t* lock_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, flushFile__stdZsyncio_u277)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE pthread_mutex_t clobber__pkgZballsZspec_u93;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
static N_INLINE(void, initRLock__coreZrlocks_u3)(pthread_mutex_t* lock_p0) {
	pthread_mutexattr_t a_1;
	nimfr_("initRLock", "/home/kang/.asdf/installs/nim/2.2.4/lib/core/rlocks.nim");
	nimlf_(27, "/home/kang/.asdf/installs/nim/2.2.4/lib/core/rlocks.nim");	nimZeroMem((void*)(&a_1), sizeof(pthread_mutexattr_t));
	nimln_(28);	pthread_mutexattr_init((&a_1));
	nimln_(29);	pthread_mutexattr_settype((&a_1), PTHREAD_MUTEX_RECURSIVE);
	nimln_(30);	pthread_mutex_init(lock_p0, (&a_1));
	popFrame();
}
N_LIB_PRIVATE N_NOCONV(void, flushStreams__pkgZballsZspec_u91)(void) {
NIM_BOOL* nimErr_;
	nimfr_("flushStreams", "/home/kang/.asdf/installs/nim/2.2.4/nimble/pkgs2/balls-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29/balls/spec.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(139, "/home/kang/.asdf/installs/nim/2.2.4/nimble/pkgs2/balls-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29/balls/spec.nim");	flushFile__stdZsyncio_u277(stderr);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotasdfatsinstallsatsnimats2dot2dot4atsnimbleatspkgs2atsballsminus6dot0dot0minus795357f7959964fe9b50a47583d4aae239fa3d29atsballsatsspecdotnim_Init000)(void) {
{
NIM_BOOL* nimErr_;
	nimfr_("spec", "/home/kang/.asdf/installs/nim/2.2.4/nimble/pkgs2/balls-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29/balls/spec.nim");
nimErr_ = nimErrorFlag();
	nimln_(144);	initRLock__coreZrlocks_u3((&clobber__pkgZballsZspec_u93));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

