/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/home/kang/.asdf/installs/nim/2.2.4/lib -I/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament -o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@spure@stimes.nim.c.o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@spure@stimes.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_TimezonecolonObjectType___MMLB1PzPhv9b9cOmzxX07wyw tyObject_TimezonecolonObjectType___MMLB1PzPhv9b9cOmzxX07wyw;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___MMLB1PzPhv9b9cOmzxX07wyw* utcInstance__pureZtimes_u2031;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___MMLB1PzPhv9b9cOmzxX07wyw* localInstance__pureZtimes_u2032;
