/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/home/kang/.asdf/installs/nim/2.2.4/lib -I/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament -o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@ssrc@snutils@sfrontpatch.nim.c.o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@ssrc@snutils@sfrontpatch.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_FileMode__5xEO6tKrUv0N6TNNETBo0w;
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef NU8 tyEnum_FileSeekPos__UlnZsjUsUkapwK2rt2ud1w;
N_LIB_PRIVATE N_NIMCALL(FILE*, open__stdZsyncio_u487)(NimStringV2 filename_p0, tyEnum_FileMode__5xEO6tKrUv0N6TNNETBo0w mode_p1, NI bufSize_p2);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine__stdZsyncio_u289)(FILE* f_p0, NimStringV2* line_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1899)(NimStringV2 s_p0, NimStringV2 sub_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimBoolToStr)(NIM_BOOL x_p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, setFilePos__stdZsyncio_u498)(FILE* f_p0, NI64 pos_p1, tyEnum_FileSeekPos__UlnZsjUsUkapwK2rt2ud1w relativeTo_p2);
N_LIB_PRIVATE N_NIMCALL(NI64, getFilePos__stdZsyncio_u521)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readLine__stdZsyncio_u318)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2714)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1);
static N_INLINE(void, writeLine__OOZOOZsrcZnutilsZfrontpatch_u19)(FILE* f_p0, NimStringV2* x_p1, NI x_p1Len_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_u254)(FILE* f_p0, NimStringV2 s_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u268)(FILE* f_p0);
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__z2VBUSK1DqrBLM39cx8gf8w_2 = { 6 | NIM_STRLIT_FLAG, "lang: " };
static const NimStringV2 TM__z2VBUSK1DqrBLM39cx8gf8w_3 = {6, (NimStrPayload*)&TM__z2VBUSK1DqrBLM39cx8gf8w_2};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__z2VBUSK1DqrBLM39cx8gf8w_5 = { 3 | NIM_STRLIT_FLAG, "---" };
static const NimStringV2 TM__z2VBUSK1DqrBLM39cx8gf8w_6 = {3, (NimStrPayload*)&TM__z2VBUSK1DqrBLM39cx8gf8w_5};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__z2VBUSK1DqrBLM39cx8gf8w_8 = { 13 | NIM_STRLIT_FLAG, "Frontmatter: " };
static const NimStringV2 TM__z2VBUSK1DqrBLM39cx8gf8w_9 = {13, (NimStrPayload*)&TM__z2VBUSK1DqrBLM39cx8gf8w_8};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__z2VBUSK1DqrBLM39cx8gf8w_10 = { 7 | NIM_STRLIT_FLAG, "Found: " };
static const NimStringV2 TM__z2VBUSK1DqrBLM39cx8gf8w_11 = {7, (NimStrPayload*)&TM__z2VBUSK1DqrBLM39cx8gf8w_10};
static const NimStringV2 TM__z2VBUSK1DqrBLM39cx8gf8w_12 = {3, (NimStrPayload*)&TM__z2VBUSK1DqrBLM39cx8gf8w_5};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__z2VBUSK1DqrBLM39cx8gf8w_15 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__z2VBUSK1DqrBLM39cx8gf8w_16 = {1, (NimStrPayload*)&TM__z2VBUSK1DqrBLM39cx8gf8w_15};
static const NimStringV2 TM__z2VBUSK1DqrBLM39cx8gf8w_17 = {6, (NimStrPayload*)&TM__z2VBUSK1DqrBLM39cx8gf8w_2};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__z2VBUSK1DqrBLM39cx8gf8w_18 = { 7 | NIM_STRLIT_FLAG, ", nice!" };
static const NimStringV2 TM__z2VBUSK1DqrBLM39cx8gf8w_19 = {7, (NimStrPayload*)&TM__z2VBUSK1DqrBLM39cx8gf8w_18};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__z2VBUSK1DqrBLM39cx8gf8w_20 = { 7 | NIM_STRLIT_FLAG, "Not in " };
static const NimStringV2 TM__z2VBUSK1DqrBLM39cx8gf8w_21 = {7, (NimStrPayload*)&TM__z2VBUSK1DqrBLM39cx8gf8w_20};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__z2VBUSK1DqrBLM39cx8gf8w_4;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__z2VBUSK1DqrBLM39cx8gf8w_4)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__z2VBUSK1DqrBLM39cx8gf8w_4);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1) {
	NI TM__z2VBUSK1DqrBLM39cx8gf8w_14;
{	(*(*dest_p0).p).data[(*dest_p0).len] = c_p1;
	if (nimAddInt((*dest_p0).len, ((NI)1), &TM__z2VBUSK1DqrBLM39cx8gf8w_14)) { raiseOverflow(); goto BeforeRet_;
	};
	(*dest_p0).len = (NI)(TM__z2VBUSK1DqrBLM39cx8gf8w_14);
	(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
static N_INLINE(void, writeLine__OOZOOZsrcZnutilsZfrontpatch_u19)(FILE* f_p0, NimStringV2* x_p1, NI x_p1Len_0) {
NIM_BOOL* nimErr_;
	nimfr_("writeLine", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	{
		NimStringV2* i_1;
		NI i_2;
		i_1 = (NimStringV2*)0;
		nimlf_(18, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators.nim");		i_2 = ((NI)0);
		{
			nimln_(19);			while (1) {
				if (!(i_2 < x_p1Len_0)) goto LA3;
				nimlf_(622, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");				if (i_2 < 0 || i_2 >= x_p1Len_0){ raiseIndexError2(i_2,x_p1Len_0-1); goto BeforeRet_;
				}
				i_1 = (&x_p1[i_2]);
				nimln_(623);				write__stdZsyncio_u254(f_p0, (*i_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(13, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators.nim");				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	nimlf_(624, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");	write__stdZsyncio_u254(f_p0, TM__z2VBUSK1DqrBLM39cx8gf8w_16);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, addLangFrontmatter__OOZOOZsrcZnutilsZfrontpatch_u2)(NimStringV2 lang_p0, NimStringV2 file_p1) {
	FILE* f_1;
	NIM_BOOL isLang_1;
	NIM_BOOL alreadyLang_1;
	NI frontmatter_1;
NIM_BOOL oldNimErrFin85_;
NIM_BOOL* nimErr_;
	nimfr_("addLangFrontmatter", "/home/kang/PARA/Areas/Programming/Nim/Nutils/src/nutils/frontpatch.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(7, "/home/kang/PARA/Areas/Programming/Nim/Nutils/src/nutils/frontpatch.nim");	f_1 = open__stdZsyncio_u487(file_p1, ((tyEnum_FileMode__5xEO6tKrUv0N6TNNETBo0w)3), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(8);	isLang_1 = NIM_FALSE;
	nimln_(9);	alreadyLang_1 = NIM_FALSE;
	nimln_(10);	frontmatter_1 = ((NI)0);
	{
		NimStringV2 line_1;
		NimStringV2 res_1;
		line_1.len = 0; line_1.p = NIM_NIL;
		res_1.len = 0; res_1.p = NIM_NIL;
		nimlf_(958, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");		res_1 = rawNewString(((NI)80));
		{
			nimln_(959);			while (1) {
				NIM_BOOL T5_;
				NimStringV2 colontmpD_;
				T5_ = (NIM_BOOL)0;
				T5_ = readLine__stdZsyncio_u289(f_1, (&res_1));
				if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
				if (!T5_) goto LA4;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				nimlf_(11, "/home/kang/PARA/Areas/Programming/Nim/Nutils/src/nutils/frontpatch.nim");				line_1 = res_1;
				nimln_(12);				{
					NimStringV2 T9_;
					NIM_BOOL T10_;
					T9_.len = 0; T9_.p = NIM_NIL;
					T9_ = rawNewString(lang_p0.len + 6);
appendString((&T9_), TM__z2VBUSK1DqrBLM39cx8gf8w_3);
appendString((&T9_), lang_p0);
					colontmpD_ = T9_;
					T10_ = (NIM_BOOL)0;
					T10_ = contains__pureZstrutils_u1899(line_1, colontmpD_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
					if (!T10_) goto LA11_;
					nimln_(13);					alreadyLang_1 = NIM_TRUE;
					nimln_(14);					nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
					if (res_1.p && !(res_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(res_1.p);
}
					goto BeforeRet_;
				}
LA11_: ;
				nimlf_(15, "/home/kang/PARA/Areas/Programming/Nim/Nutils/src/nutils/frontpatch.nim");				{
					NIM_BOOL T15_;
					NimStringV2 colontmpD__2;
					NimStringV2 colontmpD__3;
					NI TM__z2VBUSK1DqrBLM39cx8gf8w_7;
					tyArray__nHXaesL0DJZHyVS07ARPRA T19_;
					NimStringV2 T20_;
					T15_ = (NIM_BOOL)0;
					T15_ = contains__pureZstrutils_u1899(line_1, TM__z2VBUSK1DqrBLM39cx8gf8w_6);
					if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
					if (!T15_) goto LA16_;
					colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
					colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
					nimln_(16);					if (nimAddInt(frontmatter_1, ((NI)1), &TM__z2VBUSK1DqrBLM39cx8gf8w_7)) { raiseOverflow(); goto LA18_;
					};
					frontmatter_1 = (NI)(TM__z2VBUSK1DqrBLM39cx8gf8w_7);
					nimln_(17);					T20_.len = 0; T20_.p = NIM_NIL;
					colontmpD__2 = nimBoolToStr((((NI)1) <= frontmatter_1));
					T20_ = rawNewString(colontmpD__2.len + 13);
appendString((&T20_), TM__z2VBUSK1DqrBLM39cx8gf8w_9);
appendString((&T20_), colontmpD__2);
					colontmpD__3 = T20_;
					T19_[0] = colontmpD__3;
					echoBinSafe(T19_, 1);
					{
						LA18_:;
					}
					{
						nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");						if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
						if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
				}
LA16_: ;
				nimlf_(18, "/home/kang/PARA/Areas/Programming/Nim/Nutils/src/nutils/frontpatch.nim");				{
					NIM_BOOL T25_;
					NIM_BOOL T27_;
					NimStringV2 colontmpD__4;
					tyArray__nHXaesL0DJZHyVS07ARPRA T32_;
					NimStringV2 T33_;
					T25_ = (NIM_BOOL)0;
					T25_ = contains__pureZstrutils_u1899(line_1, lang_p0);
					if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
					if (!(T25_)) goto LA26_;
					T27_ = (NIM_BOOL)0;
					T27_ = (((NI)0) < frontmatter_1);
					if (!(T27_)) goto LA28_;
					T27_ = (frontmatter_1 < ((NI)3));
LA28_: ;
					T25_ = T27_;
LA26_: ;
					if (!T25_) goto LA29_;
					colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
					nimln_(19);					isLang_1 = NIM_TRUE;
					nimln_(20);					T33_.len = 0; T33_.p = NIM_NIL;
					T33_ = rawNewString(lang_p0.len + 7);
appendString((&T33_), TM__z2VBUSK1DqrBLM39cx8gf8w_11);
appendString((&T33_), lang_p0);
					colontmpD__4 = T33_;
					T32_[0] = colontmpD__4;
					echoBinSafe(T32_, 1);
					{
						LA31_:;
					}
					{
						nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");						if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
				}
LA29_: ;
				{
					LA6_:;
				}
				{
					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
			} LA4: ;
		}
		{
			LA2_:;
		}
		{
			if (res_1.p && !(res_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(res_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	nimlf_(21, "/home/kang/PARA/Areas/Programming/Nim/Nutils/src/nutils/frontpatch.nim");	{
		NIM_BOOL T42_;
		NimStringV2 colontmpD__5;
		tyArray__nHXaesL0DJZHyVS07ARPRA T75_;
		NimStringV2 T76_;
		T42_ = (NIM_BOOL)0;
		T42_ = isLang_1;
		if (!(T42_)) goto LA43_;
		T42_ = (((NI)1) <= frontmatter_1);
LA43_: ;
		if (!T42_) goto LA44_;
		colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
		nimln_(22);		setFilePos__stdZsyncio_u498(f_1, IL64(4), ((tyEnum_FileSeekPos__UlnZsjUsUkapwK2rt2ud1w)0));
		if (NIM_UNLIKELY(*nimErr_)) goto LA46_;
		{
			NimStringV2 line_2;
			NimStringV2 res_2;
			line_2.len = 0; line_2.p = NIM_NIL;
			res_2.len = 0; res_2.p = NIM_NIL;
			nimlf_(958, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");			res_2 = rawNewString(((NI)80));
			{
				nimln_(959);				while (1) {
					NIM_BOOL T51_;
					tyArray__nHXaesL0DJZHyVS07ARPRA T52_;
					T51_ = (NIM_BOOL)0;
					T51_ = readLine__stdZsyncio_u289(f_1, (&res_2));
					if (NIM_UNLIKELY(*nimErr_)) goto LA48_;
					if (!T51_) goto LA50;
					nimlf_(23, "/home/kang/PARA/Areas/Programming/Nim/Nutils/src/nutils/frontpatch.nim");					line_2 = res_2;
					nimln_(24);					T52_[0] = line_2;
					echoBinSafe(T52_, 1);
					nimln_(25);					{
						NIM_BOOL T55_;
						NimStringV2 lineAux_1;
						NimStringV2 colontmpD__6;
						NI64 T59_;
						NI64 TM__z2VBUSK1DqrBLM39cx8gf8w_13;
						NI64 savePos_1;
						tyArray__nHXaesL0DJZHyVS07ARPRA T68_;
						NimStringV2 T69_;
						tyArray__nHXaesL0DJZHyVS07ARPRA T70_;
						T55_ = (NIM_BOOL)0;
						T55_ = contains__pureZstrutils_u1899(line_2, TM__z2VBUSK1DqrBLM39cx8gf8w_12);
						if (NIM_UNLIKELY(*nimErr_)) goto LA48_;
						if (!T55_) goto LA56_;
						lineAux_1.len = 0; lineAux_1.p = NIM_NIL;
						colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
						nimln_(26);						T59_ = (NI64)0;
						T59_ = getFilePos__stdZsyncio_u521(f_1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
						if (nimSubInt64(T59_, IL64(4), &TM__z2VBUSK1DqrBLM39cx8gf8w_13)) { raiseOverflow(); goto LA58_;
						};
						setFilePos__stdZsyncio_u498(f_1, (NI64)(TM__z2VBUSK1DqrBLM39cx8gf8w_13), ((tyEnum_FileSeekPos__UlnZsjUsUkapwK2rt2ud1w)0));
						if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
						nimln_(27);						savePos_1 = getFilePos__stdZsyncio_u521(f_1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
						nimln_(28);						lineAux_1 = readLine__stdZsyncio_u318(f_1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
						{
							NimStringV2 line2_1;
							NimStringV2 colontmpD__7;
							NimStringV2 res_3;
							line2_1.len = 0; line2_1.p = NIM_NIL;
							colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
							res_3.len = 0; res_3.p = NIM_NIL;
							nimln_(29);							colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
							line2_1 = colontmpD__7;
							nimlf_(958, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");							res_3 = rawNewString(((NI)80));
							{
								nimln_(959);								while (1) {
									NIM_BOOL T64_;
									NimStringV2 T65_;
									T64_ = (NIM_BOOL)0;
									T64_ = readLine__stdZsyncio_u289(f_1, (&res_3));
									if (NIM_UNLIKELY(*nimErr_)) goto LA61_;
									if (!T64_) goto LA63;
									nimlf_(29, "/home/kang/PARA/Areas/Programming/Nim/Nutils/src/nutils/frontpatch.nim");									line2_1 = res_3;
									nimlf_(1694, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");									nimlf_(30, "/home/kang/PARA/Areas/Programming/Nim/Nutils/src/nutils/frontpatch.nim");									T65_.len = 0; T65_.p = NIM_NIL;
									T65_ = rawNewString(lineAux_1.len + line2_1.len + 1);
appendString((&T65_), lineAux_1);
appendChar((&T65_), 10);
appendString((&T65_), line2_1);
									nimlf_(1694, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");									eqsink___system_u2714((&lineAux_1), T65_);
								} LA63: ;
							}
							{
								LA61_:;
							}
							{
								nimln_(394);								if (res_3.p && !(res_3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(res_3.p);
}
								if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
							}
							if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
						}
						nimlf_(31, "/home/kang/PARA/Areas/Programming/Nim/Nutils/src/nutils/frontpatch.nim");						setFilePos__stdZsyncio_u498(f_1, savePos_1, ((tyEnum_FileSeekPos__UlnZsjUsUkapwK2rt2ud1w)0));
						if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
						nimln_(32);						T69_.len = 0; T69_.p = NIM_NIL;
						T69_ = rawNewString(lang_p0.len + 6);
appendString((&T69_), TM__z2VBUSK1DqrBLM39cx8gf8w_17);
appendString((&T69_), lang_p0);
						colontmpD__6 = T69_;
						T68_[0] = colontmpD__6;
						writeLine__OOZOOZsrcZnutilsZfrontpatch_u19(f_1, T68_, 1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
						nimln_(33);						T70_[0] = lineAux_1;
						writeLine__OOZOOZsrcZnutilsZfrontpatch_u19(f_1, T70_, 1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
						nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");						if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
						if (lineAux_1.p && !(lineAux_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(lineAux_1.p);
}
						if (res_2.p && !(res_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(res_2.p);
}
						nimlf_(34, "/home/kang/PARA/Areas/Programming/Nim/Nutils/src/nutils/frontpatch.nim");						goto LA47;
						{
							LA58_:;
						}
						{
							nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");							if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
							if (lineAux_1.p && !(lineAux_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(lineAux_1.p);
}
						}
						if (NIM_UNLIKELY(*nimErr_)) goto LA48_;
					}
LA56_: ;
				} LA50: ;
			}
			{
				LA48_:;
			}
			{
				if (res_2.p && !(res_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(res_2.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA46_;
		} LA47: ;
		nimlf_(35, "/home/kang/PARA/Areas/Programming/Nim/Nutils/src/nutils/frontpatch.nim");		T76_.len = 0; T76_.p = NIM_NIL;
		T76_ = rawNewString(lang_p0.len + 7);
appendString((&T76_), lang_p0);
appendString((&T76_), TM__z2VBUSK1DqrBLM39cx8gf8w_19);
		colontmpD__5 = T76_;
		T75_[0] = colontmpD__5;
		echoBinSafe(T75_, 1);
		{
			LA46_:;
		}
		{
			nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");			if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA40_;
LA44_: ;
	{
		NimStringV2 colontmpD__8;
		tyArray__nHXaesL0DJZHyVS07ARPRA T81_;
		NimStringV2 T82_;
		colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
		nimlf_(37, "/home/kang/PARA/Areas/Programming/Nim/Nutils/src/nutils/frontpatch.nim");		T82_.len = 0; T82_.p = NIM_NIL;
		T82_ = rawNewString(lang_p0.len + 7);
appendString((&T82_), TM__z2VBUSK1DqrBLM39cx8gf8w_21);
appendString((&T82_), lang_p0);
		colontmpD__8 = T82_;
		T81_[0] = colontmpD__8;
		echoBinSafe(T81_, 1);
		{
			LA80_:;
		}
		{
			nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");			if (colontmpD__8.p && !(colontmpD__8.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__8.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA40_: ;
	{
		LA85_:;
	}
	{
		oldNimErrFin85_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimlf_(38, "/home/kang/PARA/Areas/Programming/Nim/Nutils/src/nutils/frontpatch.nim");		close__stdZsyncio_u268(f_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin85_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
