/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/home/kang/.asdf/installs/nim/2.2.4/lib -I/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament -o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@spure@salgorithm.nim.c.o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@spure@salgorithm.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, fill__pureZstrutils_u1633)(NI* a_p0, NI a_p0Len_0, NI value_p1) {
	NI xX60gensym170__1;
	nimfr_("fill", "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/algorithm.nim");
{	nimlf_(72, "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/algorithm.nim");	xX60gensym170__1 = ((NI)0);
	{
		nimln_(98);		while (1) {
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_2;
			nimln_(73);			nimln_(98);			if (!(xX60gensym170__1 <= (a_p0Len_0-1))) goto LA2;
			nimln_(74);			if (xX60gensym170__1 < 0 || xX60gensym170__1 >= a_p0Len_0){ raiseIndexError2(xX60gensym170__1,a_p0Len_0-1); goto BeforeRet_;
			}
			nimln_(98);			a_p0[xX60gensym170__1] = value_p1;
			nimln_(75);			if (nimAddInt(xX60gensym170__1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_2)) { raiseOverflow(); goto BeforeRet_;
			};
			xX60gensym170__1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_2);
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
}
