/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/home/kang/.asdf/installs/nim/2.2.4/lib -I/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament -o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@sstd@sprivate@sospaths2.nim.c.o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@sstd@sprivate@sospaths2.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_LIB_PRIVATE N_NIMCALL(NimStringV2, normalizePath__pureZpathnorm_u150)(NimStringV2 path_p0, NIM_CHAR dirSep_p1);
N_LIB_PRIVATE N_NIMCALL(NI, parentDirPos__stdZprivateZospaths2_u163)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2714)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u8959)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__stdZprivateZospaths2_u20)(NimStringV2* path_p0, NIM_BOOL trailingSep_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8452)(NimStringV2* s_p0, NI i_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2459)(NimStringV2* s_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(void, joinPathImpl__stdZprivateZospaths2_u49)(NimStringV2* result_p0, NI* state_p1, NimStringV2 tail_p2);
static N_INLINE(NIM_CHAR, X5BX5D___system_u8400)(NimStringV2 s_p0, NI i_p1);
N_LIB_PRIVATE N_NIMCALL(void, addNormalizePath__pureZpathnorm_u86)(NimStringV2 x_p0, NimStringV2* result_p1, NI* state_p2, NIM_CHAR dirSep_p3);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_11 = { 1 | NIM_STRLIT_FLAG, "/" };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_12 = {1, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_11};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_13 = { 2 | NIM_STRLIT_FLAG, ".." };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_14 = {2, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_13};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_15 = { 1 | NIM_STRLIT_FLAG, "." };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_16 = {1, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_15};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_18 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_19 = {0, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_18};
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_20 = {1, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_15};
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI, parentDirPos__stdZprivateZospaths2_u163)(NimStringV2 path_p0) {
	NI result;
	NI q_1;
	nimfr_("parentDirPos", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");
{	nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");	q_1 = ((NI)1);
	nimln_(395);	{
		NIM_BOOL T3_;
		NI TM__O1zDbSYyG8zQytyoZAh0dg_2;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)1) <= path_p0.len);
		if (!(T3_)) goto LA4_;
		if (nimSubInt(path_p0.len, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_2)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_2) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_2) >= path_p0.len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_2),path_p0.len-1); goto BeforeRet_;
		}
		T3_ = (((NU8)(path_p0.p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_2)])) == ((NU8)(47)) || ((NU8)(path_p0.p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_2)])) == ((NU8)(47)));
LA4_: ;
		if (!T3_) goto LA5_;
		q_1 = ((NI)2);
	}
LA5_: ;
	{
		NI i_1;
		NI colontmp_;
		NI TM__O1zDbSYyG8zQytyoZAh0dg_3;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(6, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators_1.nim");		nimlf_(396, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");		if (nimSubInt(path_p0.len, q_1, &TM__O1zDbSYyG8zQytyoZAh0dg_3)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_3);
		nimlf_(33, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators_1.nim");		res_1 = colontmp_;
		{
			nimln_(34);			while (1) {
				NI TM__O1zDbSYyG8zQytyoZAh0dg_4;
				if (!(((NI)0) <= res_1)) goto LA9;
				nimlf_(396, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");				i_1 = ((NI) (res_1));
				nimln_(397);				{
					if (i_1 < 0 || i_1 >= path_p0.len){ raiseIndexError2(i_1,path_p0.len-1); goto BeforeRet_;
					}
					if (!(((NU8)(path_p0.p->data[i_1])) == ((NU8)(47)) || ((NU8)(path_p0.p->data[i_1])) == ((NU8)(47)))) goto LA12_;
					nimln_(393);					nimln_(397);					result = i_1;
					goto BeforeRet_;
				}
LA12_: ;
				nimlf_(39, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators_1.nim");				if (nimSubInt(res_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_4)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_4);
			} LA9: ;
		}
	}
	nimlf_(398, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");	result = ((NI)-1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	NI TM__O1zDbSYyG8zQytyoZAh0dg_10;
{	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	if (nimAddInt((*s_p0).len, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_10)) { raiseOverflow(); goto BeforeRet_;
	};
	(*s_p0).len = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_10);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__stdZprivateZospaths2_u20)(NimStringV2* path_p0, NIM_BOOL trailingSep_p1) {
	NI i_1;
	nimfr_("normalizePathEnd", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");
{	nimln_(51);	{
		if (!((*path_p0).len == ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(52);	i_1 = (*path_p0).len;
	{
		nimln_(53);		while (1) {
			if (!(((NI)1) <= i_1)) goto LA6;
			nimln_(54);			{
				NI TM__O1zDbSYyG8zQytyoZAh0dg_5;
				NI TM__O1zDbSYyG8zQytyoZAh0dg_6;
				if (nimSubInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_5)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_5) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_5) >= (*path_p0).len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_5),(*path_p0).len-1); goto BeforeRet_;
				}
				if (!(((NU8)((*path_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_5)])) == ((NU8)(47)) || ((NU8)((*path_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_5)])) == ((NU8)(47)))) goto LA9_;
				if (nimSubInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_6)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_6);
			}
			goto LA7_;
LA9_: ;
			{
				NIM_BOOL T12_;
				NIM_BOOL T13_;
				NI TM__O1zDbSYyG8zQytyoZAh0dg_7;
				NI TM__O1zDbSYyG8zQytyoZAh0dg_8;
				NI TM__O1zDbSYyG8zQytyoZAh0dg_9;
				nimln_(55);				T12_ = (NIM_BOOL)0;
				T13_ = (NIM_BOOL)0;
				if (nimSubInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_7)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_7) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_7) >= (*path_p0).len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_7),(*path_p0).len-1); goto BeforeRet_;
				}
				T13_ = ((NU8)((*path_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_7)]) == (NU8)(46));
				if (!(T13_)) goto LA14_;
				T13_ = (((NI)2) <= i_1);
LA14_: ;
				T12_ = T13_;
				if (!(T12_)) goto LA15_;
				if (nimSubInt(i_1, ((NI)2), &TM__O1zDbSYyG8zQytyoZAh0dg_8)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_8) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_8) >= (*path_p0).len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_8),(*path_p0).len-1); goto BeforeRet_;
				}
				T12_ = (((NU8)((*path_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_8)])) == ((NU8)(47)) || ((NU8)((*path_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_8)])) == ((NU8)(47)));
LA15_: ;
				if (!T12_) goto LA16_;
				if (nimSubInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_9)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_9);
			}
			goto LA7_;
LA16_: ;
			{
				nimln_(56);				goto LA5;
			}
LA7_: ;
		} LA6: ;
	} LA5: ;
	nimln_(57);	{
		if (!trailingSep_p1) goto LA21_;
		nimln_(59);		if ((i_1) < ((NI)0) || (i_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(i_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&(*path_p0)), (i_1));
		nimln_(61);		nimAddCharV1((&(*path_p0)), 47);
	}
	goto LA19_;
LA21_: ;
	{
		nimln_(62);		if (!(((NI)0) < i_1)) goto LA24_;
		nimln_(64);		if ((i_1) < ((NI)0) || (i_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(i_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&(*path_p0)), (i_1));
	}
	goto LA19_;
LA24_: ;
	{
		nimlf_(1694, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");		eqsink___system_u2714((&(*path_p0)), TM__O1zDbSYyG8zQytyoZAh0dg_12);
	}
LA19_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "/home/kang/.asdf/installs/nim/2.2.4/lib/system/strmantle.nim");
{	nimlf_(35, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/strmantle.nim");	result = NIM_FALSE;
	nimln_(36);	alen_1 = a_p0.len;
	nimln_(37);	blen_1 = b_p1.len;
	nimln_(38);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(39);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(34);			nimln_(39);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(40);		nimln_(34);		nimln_(40);		result = equalMem__system_u1739(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2459(s_p0);
	}
LA5_: ;
}
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8452)(NimStringV2* s_p0, NI i_p1) {
	NIM_CHAR* result;
	NI TM__O1zDbSYyG8zQytyoZAh0dg_17;
	nimfr_("[]", "/home/kang/.asdf/installs/nim/2.2.4/lib/system/indices.nim");
{	nimPrepareStrMutationV2((&(*s_p0)));
	if (nimSubInt((*s_p0).len, i_p1, &TM__O1zDbSYyG8zQytyoZAh0dg_17)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_17) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_17) >= (*s_p0).len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_17),(*s_p0).len-1); goto BeforeRet_;
	}
	result = (&(*s_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_17)]);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosparentDir)(NimStringV2 path_p0) {
	NimStringV2 result;
	NI sepPos_1;
NIM_BOOL* nimErr_;
	nimfr_("parentDir", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(423, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");	result = normalizePath__pureZpathnorm_u150(path_p0, 47);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(427);	sepPos_1 = parentDirPos__stdZprivateZospaths2_u163(result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(428);	{
		NimStringV2 T5_;
		if (!(((NI)0) <= sepPos_1)) goto LA3_;
		nimlf_(1694, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");		nimlf_(429, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");		T5_.len = 0; T5_.p = NIM_NIL;
		T5_ = substr__system_u8959(result, ((NI)0), sepPos_1);
		nimlf_(1694, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");		eqsink___system_u2714((&result), T5_);
		nimlf_(430, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");		normalizePathEnd__stdZprivateZospaths2_u20((&result), NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T7_;
		NIM_BOOL T8_;
		NIM_BOOL T9_;
		NIM_CHAR* T13_;
		nimln_(431);		T7_ = (NIM_BOOL)0;
		T8_ = (NIM_BOOL)0;
		T9_ = (NIM_BOOL)0;
		T9_ = eqStrings(result, TM__O1zDbSYyG8zQytyoZAh0dg_14);
		if (T9_) goto LA10_;
		T9_ = eqStrings(result, TM__O1zDbSYyG8zQytyoZAh0dg_16);
LA10_: ;
		T8_ = T9_;
		if (T8_) goto LA11_;
		T8_ = (result.len == ((NI)0));
LA11_: ;
		T7_ = T8_;
		if (T7_) goto LA12_;
		T13_ = (NIM_CHAR*)0;
		T13_ = X5BX5D___system_u8452((&result), ((NI)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T7_ = (((NU8)((*T13_))) == ((NU8)(47)) || ((NU8)((*T13_))) == ((NU8)(47)));
LA12_: ;
		if (!T7_) goto LA14_;
		nimlf_(1694, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");		eqsink___system_u2714((&result), TM__O1zDbSYyG8zQytyoZAh0dg_19);
	}
	goto LA1_;
LA14_: ;
	{
		eqsink___system_u2714((&result), TM__O1zDbSYyG8zQytyoZAh0dg_20);
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_CHAR, X5BX5D___system_u8400)(NimStringV2 s_p0, NI i_p1) {
	NIM_CHAR result;
	NI TM__O1zDbSYyG8zQytyoZAh0dg_22;
	nimfr_("[]", "/home/kang/.asdf/installs/nim/2.2.4/lib/system/indices.nim");
{	if (nimSubInt(s_p0.len, i_p1, &TM__O1zDbSYyG8zQytyoZAh0dg_22)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_22) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_22) >= s_p0.len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_22),s_p0.len-1); goto BeforeRet_;
	}
	result = s_p0.p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_22)];
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, joinPathImpl__stdZprivateZospaths2_u49)(NimStringV2* result_p0, NI* state_p1, NimStringV2 tail_p2) {
	NIM_BOOL trailingSep_1;
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NIM_CHAR T4_;
	NIM_BOOL T6_;
	NIM_BOOL T8_;
	NIM_CHAR* T10_;
NIM_BOOL* nimErr_;
	nimfr_("joinPathImpl", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(85, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");	T1_ = (NIM_BOOL)0;
	T2_ = (NIM_BOOL)0;
	nimln_(82);	T2_ = (((NI)0) < tail_p2.len);
	if (!(T2_)) goto LA3_;
	T4_ = (NIM_CHAR)0;
	T4_ = X5BX5D___system_u8400(tail_p2, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (((NU8)(T4_)) == ((NU8)(47)) || ((NU8)(T4_)) == ((NU8)(47)));
LA3_: ;
	T1_ = T2_;
	if (T1_) goto LA5_;
	nimln_(85);	T6_ = (NIM_BOOL)0;
	T6_ = (tail_p2.len == ((NI)0));
	if (!(T6_)) goto LA7_;
	T8_ = (NIM_BOOL)0;
	nimln_(82);	T8_ = (((NI)0) < (*result_p0).len);
	if (!(T8_)) goto LA9_;
	T10_ = (NIM_CHAR*)0;
	T10_ = X5BX5D___system_u8452(result_p0, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T8_ = (((NU8)((*T10_))) == ((NU8)(47)) || ((NU8)((*T10_))) == ((NU8)(47)));
LA9_: ;
	T6_ = T8_;
LA7_: ;
	T1_ = T6_;
LA5_: ;
	trailingSep_1 = T1_;
	nimln_(86);	normalizePathEnd__stdZprivateZospaths2_u20(result_p0, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(87);	addNormalizePath__pureZpathnorm_u86(tail_p2, result_p0, state_p1, 47);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(88);	normalizePathEnd__stdZprivateZospaths2_u20(result_p0, trailingSep_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPathOpenArray)(NimStringV2* parts_p0, NI parts_p0Len_0) {
	NimStringV2 result;
	NI estimatedLen_1;
	NI state_1;
NIM_BOOL* nimErr_;
	nimfr_("joinPath", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(153);	estimatedLen_1 = ((NI)0);
	{
		NimStringV2* p_1;
		NI i_1;
		p_1 = (NimStringV2*)0;
		nimlf_(18, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(19);			while (1) {
				NI TM__O1zDbSYyG8zQytyoZAh0dg_21;
				if (!(i_1 < parts_p0Len_0)) goto LA3;
				nimlf_(154, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");				if (i_1 < 0 || i_1 >= parts_p0Len_0){ raiseIndexError2(i_1,parts_p0Len_0-1); goto BeforeRet_;
				}
				p_1 = (&parts_p0[i_1]);
				if (nimAddInt(estimatedLen_1, (*p_1).len, &TM__O1zDbSYyG8zQytyoZAh0dg_21)) { raiseOverflow(); goto BeforeRet_;
				};
				estimatedLen_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_21);
				nimlf_(13, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators.nim");				i_1 += ((NI)1);
			} LA3: ;
		}
	}
	nimlf_(155, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");	if ((estimatedLen_1) < ((NI)0) || (estimatedLen_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(estimatedLen_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = rawNewString((estimatedLen_1));
	nimln_(156);	state_1 = ((NI)0);
	{
		NI i_2;
		NI colontmp_;
		NI res_1;
		i_2 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators_1.nim");		nimlf_(157, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");		colontmp_ = (parts_p0Len_0-1);
		nimlf_(96, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(97);			while (1) {
				NI TM__O1zDbSYyG8zQytyoZAh0dg_23;
				if (!(res_1 <= colontmp_)) goto LA6;
				nimlf_(157, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/private/ospaths2.nim");				i_2 = ((NI) (res_1));
				nimln_(158);				if (i_2 < 0 || i_2 >= parts_p0Len_0){ raiseIndexError2(i_2,parts_p0Len_0-1); goto BeforeRet_;
				}
				joinPathImpl__stdZprivateZospaths2_u49((&result), (&state_1), parts_p0[i_2]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(102, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_23)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_23);
			} LA6: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
