/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/home/kang/.asdf/installs/nim/2.2.4/lib -I/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament -o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@sstd@sassertions.nim.c.o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@sstd@sassertions.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg;
typedef struct tyObject_Defect__9cO87tuy1qb5CAJEr5a5Gsw tyObject_Defect__9cO87tuy1qb5CAJEr5a5Gsw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__3WRifCsYTwzEBSJeq60tSA tySequence__3WRifCsYTwzEBSJeq60tSA;
typedef struct tySequence__3WRifCsYTwzEBSJeq60tSA_Content tySequence__3WRifCsYTwzEBSJeq60tSA_Content;
typedef struct tyObject_StackTraceEntry__t37EfNpnik821mfIeIkUuQ tyObject_StackTraceEntry__t37EfNpnik821mfIeIkUuQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__3WRifCsYTwzEBSJeq60tSA {
  NI len; tySequence__3WRifCsYTwzEBSJeq60tSA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__3WRifCsYTwzEBSJeq60tSA trace;
	Exception* up;
};
struct tyObject_Defect__9cO87tuy1qb5CAJEr5a5Gsw {
	Exception Sup;
};
struct tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg {
	tyObject_Defect__9cO87tuy1qb5CAJEr5a5Gsw Sup;
};
struct tyObject_StackTraceEntry__t37EfNpnik821mfIeIkUuQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__3WRifCsYTwzEBSJeq60tSA_Content { NI cap; tyObject_StackTraceEntry__t37EfNpnik821mfIeIkUuQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u26)(NimStringV2 msg_p0);
static N_INLINE(void, sysFatal__stdZassertions_u28)(NimStringV2 message_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2711)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
extern TNimTypeV2 NTIv2__Xsk2vic9cj3cCxGsAlPPSXg_;
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
static N_INLINE(void, sysFatal__stdZassertions_u28)(NimStringV2 message_p1) {
	NimStringV2 colontmpD_;
	tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg* T1_;
	nimfr_("sysFatal", "/home/kang/.asdf/installs/nim/2.2.4/lib/system/fatal.nim");
{	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg*) nimNewObj(sizeof(tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg), NIM_ALIGNOF(tyObject_AssertionDefect__Xsk2vic9cj3cCxGsAlPPSXg));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__Xsk2vic9cj3cCxGsAlPPSXg_);
	(*T1_).Sup.Sup.name = "AssertionDefect";
	nimlf_(53, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/fatal.nim");	nimlf_(1694, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");	colontmpD_ = eqdup___system_u2711(message_p1);
	(*T1_).Sup.Sup.message = colontmpD_;
	nimlf_(53, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/fatal.nim");	raiseExceptionEx((Exception*)T1_, "AssertionDefect", "sysFatal", "/home/kang/.asdf/installs/nim/2.2.4/lib/system/fatal.nim", 53);
goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u26)(NimStringV2 msg_p0) {
NIM_BOOL* nimErr_;
	nimfr_("raiseAssert", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/assertions.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(36, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/assertions.nim");	sysFatal__stdZassertions_u28(msg_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0) {
NIM_BOOL* nimErr_;
	nimfr_("failedAssertImpl", "/home/kang/.asdf/installs/nim/2.2.4/lib/std/assertions.nim");
{nimErr_ = nimErrorFlag();
	nimln_(41);	raiseAssert__stdZassertions_u26(msg_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
