/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/home/kang/.asdf/installs/nim/2.2.4/lib -I/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament -o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@snimble@spkgs2@sballs-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29@sballs.nim.c.o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@snimble@spkgs2@sballs-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29@sballs.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdatomic.h>
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
typedef struct tyObject_Grenade__zFHgYrX0OQH9cQS6n32Ut9bQ tyObject_Grenade__zFHgYrX0OQH9cQS6n32Ut9bQ;
typedef struct tyObject_Atomic__iBpJQ9bQhgnM2oCGjmnXmpg tyObject_Atomic__iBpJQ9bQhgnM2oCGjmnXmpg;
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
struct tyObject_Atomic__iBpJQ9bQhgnM2oCGjmnXmpg {
	_Atomic NI64 value;
};
struct tyObject_Grenade__zFHgYrX0OQH9cQS6n32Ut9bQ {
	tyObject_Atomic__iBpJQ9bQhgnM2oCGjmnXmpg exitCode;
};
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZballs_u186)(tySequence__qwqHTkRvwhrRyENtudHQ7g* dest_p0, tySequence__qwqHTkRvwhrRyENtudHQ7g src_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, quit__system_u8309)(NI errorcode_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, load__pkgZballs_u4420)(tyObject_Atomic__iBpJQ9bQhgnM2oCGjmnXmpg* location_p0, memory_order order_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NI data[10];
} TM__9cZydDD9bOvrpaVzQHFg4t8Q_3 = {10 | NIM_STRLIT_FLAG, {((NI)0),
((NI)0),
((NI)0),
((NI)0),
((NI)0),
((NI)0),
((NI)0),
((NI)0),
((NI)0),
((NI)0)}};
static NIM_CONST tySequence__qwqHTkRvwhrRyENtudHQ7g TM__9cZydDD9bOvrpaVzQHFg4t8Q_2 = {10, (tySequence__qwqHTkRvwhrRyENtudHQ7g_Content*)&TM__9cZydDD9bOvrpaVzQHFg4t8Q_3};
N_LIB_PRIVATE tySequence__qwqHTkRvwhrRyENtudHQ7g testResults__pkgZballs_u219;
N_LIB_PRIVATE tyObject_Grenade__zFHgYrX0OQH9cQS6n32Ut9bQ grenade__pkgZballs_u4478;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
static N_INLINE(void, quit__system_u8309)(NI errorcode_p0) {
	nimfr_("quit", "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");
	nimlf_(2448, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");	{
		if (!(errorcode_p0 < ((NI)-128))) goto LA3_;
		nimln_(2449);		exit(((int)-128));
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(2450);		if (!(((NI)127) < errorcode_p0)) goto LA6_;
		nimln_(2451);		exit(((int)127));
	}
	goto LA1_;
LA6_: ;
	{
		nimln_(2453);		exit(((int) (errorcode_p0)));
	}
LA1_: ;
	popFrame();
}
static N_INLINE(NI, load__pkgZballs_u4420)(tyObject_Atomic__iBpJQ9bQhgnM2oCGjmnXmpg* location_p0, memory_order order_p1) {
	NI result;
	NI64 T1_;
	nimfr_("load", "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/concurrency/atomics.nim");
	nimlf_(354, "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/concurrency/atomics.nim");	T1_ = (NI64)0;
	T1_ = atomic_load_explicit((&(*location_p0).value), order_p1);
	result = ((NI) (T1_));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZballs_u4409)(tyObject_Grenade__zFHgYrX0OQH9cQS6n32Ut9bQ grenade_p0) {
	tyObject_Atomic__iBpJQ9bQhgnM2oCGjmnXmpg* p_1;
	NI T1_;
NIM_BOOL* nimErr_;
	nimfr_("=destroy", "/home/kang/.asdf/installs/nim/2.2.4/nimble/pkgs2/balls-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29/balls.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(387, "/home/kang/.asdf/installs/nim/2.2.4/nimble/pkgs2/balls-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29/balls.nim");	p_1 = (&grenade_p0.exitCode);
	nimln_(388);	T1_ = (NI)0;
	T1_ = load__pkgZballs_u4420(p_1, ((memory_order)5));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	quit__system_u8309(T1_);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotasdfatsinstallsatsnimats2dot2dot4atsnimbleatspkgs2atsballsminus6dot0dot0minus795357f7959964fe9b50a47583d4aae239fa3d29atsballsdotnim_Init000)(void) {
{
	nimfr_("balls", "/home/kang/.asdf/installs/nim/2.2.4/nimble/pkgs2/balls-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29/balls.nim");
	nimlf_(651, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");	eqcopy___pkgZballs_u186((&testResults__pkgZballs_u219), TM__9cZydDD9bOvrpaVzQHFg4t8Q_2);
	nimlf_(390, "/home/kang/.asdf/installs/nim/2.2.4/nimble/pkgs2/balls-6.0.0-795357f7959964fe9b50a47583d4aae239fa3d29/balls.nim");	nimZeroMem((void*)(&grenade__pkgZballs_u4478), sizeof(tyObject_Grenade__zFHgYrX0OQH9cQS6n32Ut9bQ));
	nimTestErrorFlag();
	popFrame();
}
}

