/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/home/kang/.asdf/installs/nim/2.2.4/lib -I/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament -o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@spure@sterminal.nim.c.o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@spure@sterminal.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <unistd.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_PTerminalcolonObjectType___ymYxTI9av1IkUYG0bBVibcg tyObject_PTerminalcolonObjectType___ymYxTI9av1IkUYG0bBVibcg;
N_LIB_PRIVATE N_NIMCALL(int, getFileHandle__stdZsyncio_u279)(FILE* f_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE NIM_THREADVAR tyObject_PTerminalcolonObjectType___ymYxTI9av1IkUYG0bBVibcg* gTerm__pureZterminal_u10;
N_LIB_PRIVATE NIM_THREADVAR NI gFG__pureZterminal_u362;
N_LIB_PRIVATE NIM_THREADVAR NI gBG__pureZterminal_u363;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isatty__pureZterminal_u625)(FILE* f_p0) {
	NIM_BOOL result;
	int T1_;
	int T2_;
NIM_BOOL* nimErr_;
	nimfr_("isatty", "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/terminal.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(812, "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/terminal.nim");	T1_ = (int)0;
	T1_ = getFileHandle__stdZsyncio_u279(f_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (int)0;
	T2_ = isatty(T1_);
	result = !((T2_ == ((NI32)0)));
	}BeforeRet_: ;
	popFrame();
	return result;
}
