/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/home/kang/.asdf/installs/nim/2.2.4/lib -I/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament -o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@spure@sstrutils.nim.c.o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@m..@s..@s..@s..@s..@s..@s..@s.asdf@sinstalls@snim@s2.2.4@slib@spure@sstrutils.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#define _GNU_SOURCE
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NI tyArray__9cc9aPiDa8VaWjVcFLabEDZQ[256];
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1);
N_LIB_PRIVATE N_NIMCALL(void, fill__pureZstrutils_u1633)(NI* a_p0, NI a_p0Len_0, NI value_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/home/kang/.asdf/installs/nim/2.2.4/lib/system/arithmetics.nim");
	nimlf_(364, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI length_1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_3;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_4;
	nimfr_("find", "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/strutils.nim");
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimlf_(1971, "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/strutils.nim");	result = ((NI)-1);
	nimln_(1972);	{
		if (!(last_p3 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p0.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p3;
		last_2 = colontmpD__2;
	}
LA1_: ;
	nimln_(1983);	if (nimSubInt(last_2, start_p2, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_3)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_3), ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_4)) { raiseOverflow(); goto BeforeRet_;
	};
	length_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4);
	nimln_(1984);	{
		void* found_1;
		if (!(((NI)0) < length_1)) goto LA8_;
		nimln_(1985);		if (start_p2 < 0 || start_p2 >= s_p0.len){ raiseIndexError2(start_p2,s_p0.len-1); goto BeforeRet_;
		}
		found_1 = memchr(((void*) ((&s_p0.p->data[start_p2]))), ((int) (((NU8)(sub_p1)))), ((size_t) (length_1)));
		nimln_(1986);		{
			if (!!((found_1 == 0))) goto LA12_;
			nimln_(1987);			nimln_(1959);			nimln_(1987);			result = minuspercent___system_u813(((NI) (ptrdiff_t) (found_1)), ((NI) (nimToCStringConv(s_p0))));
			goto BeforeRet_;
		}
LA12_: ;
	}
LA8_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI subLast_1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_6;
	NI skip_1;
	nimfr_("find", "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/strutils.nim");
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimln_(1931);	{
		if (!(last_p4 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p1.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p4;
		last_2 = colontmpD__2;
	}
LA1_: ;
	nimln_(1932);	if (nimSubInt(sub_p2.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_6)) { raiseOverflow(); goto BeforeRet_;
	};
	subLast_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6);
	nimln_(1934);	{
		if (!(subLast_1 == ((NI)-1))) goto LA8_;
		nimln_(1937);		nimln_(1919);		nimln_(1937);		result = start_p3;
		goto BeforeRet_;
	}
LA8_: ;
	nimln_(1941);	result = ((NI)-1);
	nimln_(1942);	skip_1 = start_p3;
	{
		nimln_(1944);		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_7;
			NI i_1;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_10;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_11;
			if (nimSubInt(last_2, skip_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_7)) { raiseOverflow(); goto BeforeRet_;
			};
			if (!(subLast_1 <= (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_7))) goto LA11;
			nimln_(1945);			i_1 = subLast_1;
			{
				nimln_(1946);				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_8;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_9;
					if (nimAddInt(skip_1, i_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_8)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_8) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_8) >= s_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_8),s_p1.len-1); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= sub_p2.len){ raiseIndexError2(i_1,sub_p2.len-1); goto BeforeRet_;
					}
					if (!((NU8)(s_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_8)]) == (NU8)(sub_p2.p->data[i_1]))) goto LA13;
					nimln_(1947);					{
						if (!(i_1 == ((NI)0))) goto LA16_;
						nimln_(1948);						nimln_(1919);						nimln_(1948);						result = skip_1;
						goto BeforeRet_;
					}
LA16_: ;
					nimln_(1949);					if (nimSubInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_9)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_9);
				} LA13: ;
			}
			nimln_(1950);			if (nimAddInt(skip_1, subLast_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_10)) { raiseOverflow(); goto BeforeRet_;
			};
			if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_10) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_10) >= s_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_10),s_p1.len-1); goto BeforeRet_;
			}
			if (nimAddInt(skip_1, a_p0[(((NU8)(s_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_10)])))- 0], &TM__JGc9b9bh2D3nTdUR7TGyq8aA_11)) { raiseOverflow(); goto BeforeRet_;
			};
			if (TM__JGc9b9bh2D3nTdUR7TGyq8aA_11 < 0 || TM__JGc9b9bh2D3nTdUR7TGyq8aA_11 > IL64(9223372036854775807)){ raiseOverflow(); goto BeforeRet_;
			}
			skip_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11);
		} LA11: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1) {
	NI m_1;
NIM_BOOL* nimErr_;
	nimfr_("initSkipTable", "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(1904);	m_1 = sub_p1.len;
	nimln_(1905);	fill__pureZstrutils_u1633(a_p0, 256, m_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_12;
		NI i_2;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(126, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators_1.nim");		nimlf_(1907, "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/strutils.nim");		if (nimSubInt(m_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_12)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_12);
		nimlf_(128, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators_1.nim");		i_2 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_13;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_14;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_15;
				if (!(i_2 < colontmp_)) goto LA3;
				nimlf_(1907, "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/strutils.nim");				i_1 = i_2;
				nimln_(1908);				if (i_1 < 0 || i_1 >= sub_p1.len){ raiseIndexError2(i_1,sub_p1.len-1); goto BeforeRet_;
				}
				if (nimSubInt(m_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_13)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_13), i_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_14)) { raiseOverflow(); goto BeforeRet_;
				};
				a_p0[(((NU8)(sub_p1.p->data[i_1])))- 0] = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_14);
				nimlf_(131, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_15)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_15);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result) {
NIM_BOOL* nimErr_;
	nimfr_("initSkipTable", "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(1917, "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/strutils.nim");	nsuInitSkipTable(Result, sub_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NI start_p2, NI last_p3) {
	NI result;
	NI subLen_1;
NIM_BOOL* nimErr_;
	nimfr_("find", "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(2029);	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_2;
		if (nimSubInt(s_p0.len, start_p2, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_2)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2) < sub_p1.len)) goto LA3_;
		nimln_(2017);		nimln_(2029);		result = ((NI)-1);
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(2030);	{
		if (!(sub_p1.len == ((NI)1))) goto LA7_;
		nimln_(2017);		nimln_(2030);		if (((NI)0) < 0 || ((NI)0) >= sub_p1.len){ raiseIndexError2(((NI)0),sub_p1.len-1); goto BeforeRet_;
		}
		result = nsuFindChar(s_p0, sub_p1.p->data[((NI)0)], start_p2, last_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA7_: ;
	nimln_(2039);	subLen_1 = sub_p1.len;
	nimln_(2040);	{
		NIM_BOOL T11_;
		NIM_BOOL T12_;
		NI colontmpD_;
		NI colontmpD__2;
		void* found_1;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_5;
		T11_ = (NIM_BOOL)0;
		T12_ = (NIM_BOOL)0;
		T12_ = (last_p3 < ((NI)0));
		if (!(T12_)) goto LA13_;
		T12_ = (start_p2 < s_p0.len);
LA13_: ;
		T11_ = T12_;
		if (!(T11_)) goto LA14_;
		T11_ = !((subLen_1 == ((NI)0)));
LA14_: ;
		if (!T11_) goto LA15_;
		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		nimln_(2041);		if (start_p2 < 0 || start_p2 >= s_p0.len){ raiseIndexError2(start_p2,s_p0.len-1); goto BeforeRet_;
		}
		if (nimSubInt(s_p0.len, start_p2, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_5)) { raiseOverflow(); goto BeforeRet_;
		};
		found_1 = memmem(((void*) ((&s_p0.p->data[start_p2]))), ((size_t) ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_5))), ((void*) (nimToCStringConv(sub_p1))), ((size_t) (subLen_1)));
		nimln_(2042);		{
			if (!!((found_1 == 0))) goto LA19_;
			nimln_(2043);			colontmpD_ = minuspercent___system_u813(((NI) (ptrdiff_t) (found_1)), ((NI) (nimToCStringConv(s_p0))));
			result = colontmpD_;
		}
		goto LA17_;
LA19_: ;
		{
			nimln_(2045);			colontmpD__2 = ((NI)-1);
			result = colontmpD__2;
		}
LA17_: ;
	}
	goto LA9_;
LA15_: ;
	{
		tyArray__9cc9aPiDa8VaWjVcFLabEDZQ T23_;
		nimln_(2033);		nimZeroMem((void*)T23_, sizeof(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ));
		nsuInitNewSkipTable(sub_p1, T23_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = nsuFindStrA(T23_, s_p0, sub_p1, start_p2, last_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1899)(NimStringV2 s_p0, NimStringV2 sub_p1) {
	NIM_BOOL result;
	NI T1_;
NIM_BOOL* nimErr_;
	nimfr_("contains", "/home/kang/.asdf/installs/nim/2.2.4/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(2187);	nimln_(2182);	nimln_(2187);	T1_ = (NI)0;
	T1_ = nsuFindStr(s_p0, sub_p1, ((NI)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
