/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/home/kang/.asdf/installs/nim/2.2.4/lib -I/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament -o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@mhelper.nim.c.o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@mhelper.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyTuple__GGKW7Caq8ukhZanTky59bXg tyTuple__GGKW7Caq8ukhZanTky59bXg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__GGKW7Caq8ukhZanTky59bXg {
	FILE* Field0;
	FILE* Field1;
};
typedef NimStringV2 tyArray__24KAM9afIUgUaqBaEBB6r9bg[3];
typedef NimStringV2 tyArray__Re75IspeoxXy2oCZHwcRrA[2];
typedef NU8 tyEnum_FileMode__5xEO6tKrUv0N6TNNETBo0w;
typedef NU8 tyArray__YtcvxHNKV4YiecPE9ap1mcA[20];
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosparentDir)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPathOpenArray)(NimStringV2* parts_p0, NI parts_p0Len_0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(FILE*, open__stdZsyncio_u487)(NimStringV2 filename_p0, tyEnum_FileMode__5xEO6tKrUv0N6TNNETBo0w mode_p1, NI bufSize_p2);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine__stdZsyncio_u289)(FILE* f_p0, NimStringV2* line_p1);
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u268)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readLine__stdZsyncio_u318)(FILE* f_p0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___stdZsha1_u995)(tyArray__YtcvxHNKV4YiecPE9ap1mcA a_p0, tyArray__YtcvxHNKV4YiecPE9ap1mcA b_p1);
N_LIB_PRIVATE N_NIMCALL(void, secureHashFile__stdZsha1_u945)(NimStringV2 filename_p0, tyArray__YtcvxHNKV4YiecPE9ap1mcA Result);
static const struct {
  NI cap; NIM_CHAR data[71+1];
} TM__Ro3OWxDwEUDzQ27EkEIUbA_2 = { 71 | NIM_STRLIT_FLAG, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/helper.nim" };
static const NimStringV2 TM__Ro3OWxDwEUDzQ27EkEIUbA_3 = {71, (NimStrPayload*)&TM__Ro3OWxDwEUDzQ27EkEIUbA_2};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__Ro3OWxDwEUDzQ27EkEIUbA_4 = { 19 | NIM_STRLIT_FLAG, "expected_frontpatch" };
static const NimStringV2 TM__Ro3OWxDwEUDzQ27EkEIUbA_5 = {19, (NimStrPayload*)&TM__Ro3OWxDwEUDzQ27EkEIUbA_4};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__Ro3OWxDwEUDzQ27EkEIUbA_6 = { 9 | NIM_STRLIT_FLAG, "expected_" };
static const NimStringV2 TM__Ro3OWxDwEUDzQ27EkEIUbA_7 = {9, (NimStrPayload*)&TM__Ro3OWxDwEUDzQ27EkEIUbA_6};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__Ro3OWxDwEUDzQ27EkEIUbA_9 = { 3 | NIM_STRLIT_FLAG, ".md" };
static const NimStringV2 TM__Ro3OWxDwEUDzQ27EkEIUbA_10 = {3, (NimStrPayload*)&TM__Ro3OWxDwEUDzQ27EkEIUbA_9};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__Ro3OWxDwEUDzQ27EkEIUbA_11 = { 19 | NIM_STRLIT_FLAG, "obtained_frontpatch" };
static const NimStringV2 TM__Ro3OWxDwEUDzQ27EkEIUbA_12 = {19, (NimStrPayload*)&TM__Ro3OWxDwEUDzQ27EkEIUbA_11};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__Ro3OWxDwEUDzQ27EkEIUbA_13 = { 9 | NIM_STRLIT_FLAG, "obtained_" };
static const NimStringV2 TM__Ro3OWxDwEUDzQ27EkEIUbA_14 = {9, (NimStrPayload*)&TM__Ro3OWxDwEUDzQ27EkEIUbA_13};
static const NimStringV2 TM__Ro3OWxDwEUDzQ27EkEIUbA_15 = {3, (NimStrPayload*)&TM__Ro3OWxDwEUDzQ27EkEIUbA_9};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__Ro3OWxDwEUDzQ27EkEIUbA_16 = { 15 | NIM_STRLIT_FLAG, "Expected path: " };
static const NimStringV2 TM__Ro3OWxDwEUDzQ27EkEIUbA_17 = {15, (NimStrPayload*)&TM__Ro3OWxDwEUDzQ27EkEIUbA_16};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__Ro3OWxDwEUDzQ27EkEIUbA_18 = { 15 | NIM_STRLIT_FLAG, "Obtained path: " };
static const NimStringV2 TM__Ro3OWxDwEUDzQ27EkEIUbA_19 = {15, (NimStrPayload*)&TM__Ro3OWxDwEUDzQ27EkEIUbA_18};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__Ro3OWxDwEUDzQ27EkEIUbA_8;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__Ro3OWxDwEUDzQ27EkEIUbA_8)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__Ro3OWxDwEUDzQ27EkEIUbA_8);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__GGKW7Caq8ukhZanTky59bXg, openFilesToTest__helper_u4)(NimStringV2 name_p0) {
	tyTuple__GGKW7Caq8ukhZanTky59bXg result;
	NimStringV2 testsDir_1;
	NimStringV2 expPath_1;
	NimStringV2 colontmpD_;
	NimStringV2 obtPath_1;
	NimStringV2 colontmpD__2;
	tyArray__24KAM9afIUgUaqBaEBB6r9bg T2_;
	NimStringV2 T3_;
	tyArray__24KAM9afIUgUaqBaEBB6r9bg T4_;
	NimStringV2 T5_;
	tyArray__Re75IspeoxXy2oCZHwcRrA T6_;
	tyArray__Re75IspeoxXy2oCZHwcRrA T7_;
	FILE* T8_;
	FILE* T9_;
NIM_BOOL* nimErr_;
	nimfr_("openFilesToTest", "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/helper.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyTuple__GGKW7Caq8ukhZanTky59bXg));
	testsDir_1.len = 0; testsDir_1.p = NIM_NIL;
	expPath_1.len = 0; expPath_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	obtPath_1.len = 0; obtPath_1.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimlf_(6, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/helper.nim");	testsDir_1 = nosparentDir(TM__Ro3OWxDwEUDzQ27EkEIUbA_3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(7);	T2_[0] = testsDir_1;
	T2_[1] = TM__Ro3OWxDwEUDzQ27EkEIUbA_5;
	T3_.len = 0; T3_.p = NIM_NIL;
	T3_ = rawNewString(name_p0.len + 12);
appendString((&T3_), TM__Ro3OWxDwEUDzQ27EkEIUbA_7);
appendString((&T3_), name_p0);
appendString((&T3_), TM__Ro3OWxDwEUDzQ27EkEIUbA_10);
	colontmpD_ = T3_;
	T2_[2] = colontmpD_;
	expPath_1 = nosjoinPathOpenArray(T2_, 3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(8);	T4_[0] = testsDir_1;
	T4_[1] = TM__Ro3OWxDwEUDzQ27EkEIUbA_12;
	T5_.len = 0; T5_.p = NIM_NIL;
	T5_ = rawNewString(name_p0.len + 12);
appendString((&T5_), TM__Ro3OWxDwEUDzQ27EkEIUbA_14);
appendString((&T5_), name_p0);
appendString((&T5_), TM__Ro3OWxDwEUDzQ27EkEIUbA_15);
	colontmpD__2 = T5_;
	T4_[2] = colontmpD__2;
	obtPath_1 = nosjoinPathOpenArray(T4_, 3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(9);	T6_[0] = TM__Ro3OWxDwEUDzQ27EkEIUbA_17;
	T6_[1] = expPath_1;
	echoBinSafe(T6_, 2);
	nimln_(10);	T7_[0] = TM__Ro3OWxDwEUDzQ27EkEIUbA_19;
	T7_[1] = obtPath_1;
	echoBinSafe(T7_, 2);
	nimln_(11);	T8_ = (FILE*)0;
	T8_ = open__stdZsyncio_u487(expPath_1, ((tyEnum_FileMode__5xEO6tKrUv0N6TNNETBo0w)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result.Field0 = T8_;
	T9_ = (FILE*)0;
	T9_ = open__stdZsyncio_u487(obtPath_1, ((tyEnum_FileMode__5xEO6tKrUv0N6TNNETBo0w)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result.Field1 = T9_;
	{
		LA1_:;
	}
	{
		nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (obtPath_1.p && !(obtPath_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(obtPath_1.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (expPath_1.p && !(expPath_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(expPath_1.p);
}
		if (testsDir_1.p && !(testsDir_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(testsDir_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, countLines__helper_u104)(NimStringV2 filename_p0) {
	NI result;
NIM_BOOL oldNimErrFin2_;
NIM_BOOL* nimErr_;
	nimfr_("countLines", "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/helper.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		NimStringV2 __1;
		FILE* f_1;
		NimStringV2 res_1;
		__1.len = 0; __1.p = NIM_NIL;
		nimlf_(939, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");		f_1 = open__stdZsyncio_u487(filename_p0, ((tyEnum_FileMode__5xEO6tKrUv0N6TNNETBo0w)0), ((NI)8000));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		res_1.len = 0; res_1.p = NIM_NIL;
		nimln_(941);		res_1 = rawNewString(((NI)80));
		{
			nimln_(942);			while (1) {
				NIM_BOOL T6_;
				NI TM__Ro3OWxDwEUDzQ27EkEIUbA_20;
				T6_ = (NIM_BOOL)0;
				T6_ = readLine__stdZsyncio_u289(f_1, (&res_1));
				if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
				if (!T6_) goto LA5;
				nimlf_(14, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/helper.nim");				__1 = res_1;
				if (nimAddInt(result, ((NI)1), &TM__Ro3OWxDwEUDzQ27EkEIUbA_20)) { raiseOverflow(); goto LA3_;
				};
				result = (NI)(TM__Ro3OWxDwEUDzQ27EkEIUbA_20);
			} LA5: ;
		}
		{
			LA3_:;
		}
		{
			nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");			if (res_1.p && !(res_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(res_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
		{
			LA2_:;
		}
		{
			oldNimErrFin2_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(944, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");			close__stdZsyncio_u268(f_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			*nimErr_ = oldNimErrFin2_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "/home/kang/.asdf/installs/nim/2.2.4/lib/system/strmantle.nim");
{	nimlf_(35, "/home/kang/.asdf/installs/nim/2.2.4/lib/system/strmantle.nim");	result = NIM_FALSE;
	nimln_(36);	alen_1 = a_p0.len;
	nimln_(37);	blen_1 = b_p1.len;
	nimln_(38);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(39);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(34);			nimln_(39);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(40);		nimln_(34);		nimln_(40);		result = equalMem__system_u1739(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, allLinesEqual__helper_u113)(NimStringV2 filename1_p0, NimStringV2 filename2_p1) {
	NIM_BOOL result;
	FILE* f1_1;
	FILE* f2_1;
NIM_BOOL oldNimErrFin2_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("allLinesEqual", "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/helper.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(18, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/helper.nim");	f1_1 = open__stdZsyncio_u487(filename1_p0, ((tyEnum_FileMode__5xEO6tKrUv0N6TNNETBo0w)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(19);	f2_1 = open__stdZsyncio_u487(filename2_p1, ((tyEnum_FileMode__5xEO6tKrUv0N6TNNETBo0w)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NimStringV2 line_1;
		NimStringV2 res_1;
		line_1.len = 0; line_1.p = NIM_NIL;
		res_1.len = 0; res_1.p = NIM_NIL;
		nimlf_(958, "/home/kang/.asdf/installs/nim/2.2.4/lib/std/syncio.nim");		res_1 = rawNewString(((NI)80));
		{
			nimln_(959);			while (1) {
				NIM_BOOL T7_;
				NimStringV2 colontmpD_;
				T7_ = (NIM_BOOL)0;
				T7_ = readLine__stdZsyncio_u289(f1_1, (&res_1));
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				if (!T7_) goto LA6;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				nimlf_(22, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/helper.nim");				line_1 = res_1;
				nimln_(23);				{
					colontmpD_ = readLine__stdZsyncio_u318(f2_1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
					if (!!(eqStrings(line_1, colontmpD_))) goto LA11_;
					nimln_(24);					nimln_(17);					nimln_(24);					result = NIM_FALSE;
					nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
					if (res_1.p && !(res_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(res_1.p);
}
					nimlf_(21, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/helper.nim");					close__stdZsyncio_u268(f2_1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					nimln_(20);					close__stdZsyncio_u268(f1_1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					goto BeforeRet_;
				}
LA11_: ;
				{
					LA8_:;
				}
				{
					nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			} LA6: ;
		}
		{
			LA4_:;
		}
		{
			if (res_1.p && !(res_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(res_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
	}
	nimlf_(25, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/helper.nim");	nimln_(17);	nimln_(25);	result = NIM_TRUE;
	nimln_(21);	close__stdZsyncio_u268(f2_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(20);	close__stdZsyncio_u268(f1_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA2_:;
	}
	{
		oldNimErrFin2_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimln_(21);		close__stdZsyncio_u268(f2_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		*nimErr_ = oldNimErrFin2_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimln_(20);		close__stdZsyncio_u268(f1_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, filesMatch__helper_u120)(NimStringV2 file1_p0, NimStringV2 file2_p1) {
	NIM_BOOL result;
	tyArray__YtcvxHNKV4YiecPE9ap1mcA T1_;
	tyArray__YtcvxHNKV4YiecPE9ap1mcA T2_;
NIM_BOOL* nimErr_;
	nimfr_("filesMatch", "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/helper.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(28);	nimZeroMem((void*)T1_, sizeof(tyArray__YtcvxHNKV4YiecPE9ap1mcA));
	secureHashFile__stdZsha1_u945(file1_p0, T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)T2_, sizeof(tyArray__YtcvxHNKV4YiecPE9ap1mcA));
	secureHashFile__stdZsha1_u945(file2_p1, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = eqeq___stdZsha1_u995(T1_, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
