/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/home/kang/.asdf/installs/nim/2.2.4/lib -I/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament -o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@mtest1.nim.c.o /home/kang/PARA/Areas/Programming/Nim/Nutils/nimcache/tests/testament/test1.nim_4a8a08f09d37b73795649038408b5f33/@mtest1.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__GGKW7Caq8ukhZanTky59bXg tyTuple__GGKW7Caq8ukhZanTky59bXg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct tyTuple__GGKW7Caq8ukhZanTky59bXg {
	FILE* Field0;
	FILE* Field1;
};
typedef NimStringV2 tyArray__Re75IspeoxXy2oCZHwcRrA[2];
N_LIB_PRIVATE N_NIMCALL(void, setStdIoUnbuffered__stdZsyncio_u528)(void);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, addLangFrontmatter__OOZOOZsrcZnutilsZfrontpatch_u2)(NimStringV2 lang_p0, NimStringV2 file_p1);
N_LIB_PRIVATE N_NIMCALL(tyTuple__GGKW7Caq8ukhZanTky59bXg, openFilesToTest__helper_u4)(NimStringV2 name_p0);
N_LIB_PRIVATE N_NIMCALL(NI, countLines__helper_u104)(NimStringV2 filename_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, allLinesEqual__helper_u113)(NimStringV2 filename1_p0, NimStringV2 filename2_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimBoolToStr)(NIM_BOOL x_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, filesMatch__helper_u120)(NimStringV2 file1_p0, NimStringV2 file2_p1);
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u268)(FILE* f_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotasdfatsinstallsatsnimats2dot2dot4atslibatssystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_3 = { 26 | NIM_STRLIT_FLAG, "addLangFrontmatter no_lang" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_4 = { 7 | NIM_STRLIT_FLAG, "no_lang" };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_5 = {7, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_4};
static const struct {
  NI cap; NIM_CHAR data[55+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_6 = { 55 | NIM_STRLIT_FLAG, "tests/testament/obtained_frontpatch/obtained_no_lang.md" };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_7 = {55, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_6};
static const struct {
  NI cap; NIM_CHAR data[55+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_8 = { 55 | NIM_STRLIT_FLAG, "tests/testament/expected_frontpatch/expected_no_lang.md" };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_9 = {55, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_8};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_10 = { 16 | NIM_STRLIT_FLAG, "Total of lines: " };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_11 = {16, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_10};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_13 = { 24 | NIM_STRLIT_FLAG, " \342\206\220 input | output \342\206\222 " };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_14 = {24, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_13};
static const struct {
  NI cap; NIM_CHAR data[95+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_15 = { 95 | NIM_STRLIT_FLAG, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/test1.nim(26, 5) `num_i == num_o` " };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_16 = {95, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_15};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_17 = { 13 | NIM_STRLIT_FLAG, "Lines Equal: " };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_18 = {13, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_17};
static const struct {
  NI cap; NIM_CHAR data[99+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_19 = { 99 | NIM_STRLIT_FLAG, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/test1.nim(31, 7) `equalLines == true` " };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_20 = {99, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_19};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_21 = { 11 | NIM_STRLIT_FLAG, "ByteMatch: " };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_22 = {11, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_21};
static const struct {
  NI cap; NIM_CHAR data[99+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_23 = { 99 | NIM_STRLIT_FLAG, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/test1.nim(36, 7) `byteToByte == true` " };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_24 = {99, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_23};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_26 = { 21 | NIM_STRLIT_FLAG, "addLangFrontmatter es" };
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_27 = { 2 | NIM_STRLIT_FLAG, "es" };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_28 = {2, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_27};
static const struct {
  NI cap; NIM_CHAR data[45+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_29 = { 45 | NIM_STRLIT_FLAG, "tests/testament/obtained_frontpatch/obtained_" };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_30 = {45, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_29};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_31 = { 3 | NIM_STRLIT_FLAG, ".md" };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_32 = {3, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_31};
static const struct {
  NI cap; NIM_CHAR data[45+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_33 = { 45 | NIM_STRLIT_FLAG, "tests/testament/expected_frontpatch/expected_" };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_34 = {45, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_33};
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_35 = {3, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_31};
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_36 = {16, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_10};
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_37 = {24, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_13};
static const struct {
  NI cap; NIM_CHAR data[95+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_38 = { 95 | NIM_STRLIT_FLAG, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/test1.nim(58, 5) `num_i == num_o` " };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_39 = {95, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_38};
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_40 = {13, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_17};
static const struct {
  NI cap; NIM_CHAR data[99+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_41 = { 99 | NIM_STRLIT_FLAG, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/test1.nim(63, 5) `equalLines == true` " };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_42 = {99, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_41};
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_43 = {11, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_21};
static const struct {
  NI cap; NIM_CHAR data[99+1];
} TM__uARDeQU6tlhDvrSyWmbOoQ_44 = { 99 | NIM_STRLIT_FLAG, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/test1.nim(68, 7) `byteToByte == true` " };
static const NimStringV2 TM__uARDeQU6tlhDvrSyWmbOoQ_45 = {99, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_44};
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__uARDeQU6tlhDvrSyWmbOoQ_2 = {{26, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_3}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__uARDeQU6tlhDvrSyWmbOoQ_25 = {{21, (NimStrPayload*)&TM__uARDeQU6tlhDvrSyWmbOoQ_26}}
;
N_LIB_PRIVATE NimStringV2 fileTest__test1_u5;
N_LIB_PRIVATE NimStringV2 fileOutput__test1_u6;
N_LIB_PRIVATE NimStringV2 fileExpected__test1_u7;
N_LIB_PRIVATE FILE* f_e__test1_u9;
N_LIB_PRIVATE FILE* f_o__test1_u10;
N_LIB_PRIVATE NimStringV2 totalOfLines__test1_u14;
N_LIB_PRIVATE NI num_i__test1_u12;
N_LIB_PRIVATE NI num_o__test1_u13;
N_LIB_PRIVATE NIM_BOOL equalLines__test1_u21;
N_LIB_PRIVATE NIM_BOOL byteToByte__test1_u28;
N_LIB_PRIVATE NimStringV2 fileTest__test1_u35;
N_LIB_PRIVATE NimStringV2 fileOutput__test1_u36;
N_LIB_PRIVATE NimStringV2 fileExpected__test1_u37;
N_LIB_PRIVATE FILE* f_e__test1_u39;
N_LIB_PRIVATE FILE* f_o__test1_u40;
N_LIB_PRIVATE NimStringV2 totalOfLines__test1_u44;
N_LIB_PRIVATE NI num_i__test1_u42 = ((NI)0);
N_LIB_PRIVATE NI num_o__test1_u43 = ((NI)0);
N_LIB_PRIVATE NIM_BOOL equalLines__test1_u51;
N_LIB_PRIVATE NIM_BOOL byteToByte__test1_u58;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__uARDeQU6tlhDvrSyWmbOoQ_12;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__uARDeQU6tlhDvrSyWmbOoQ_12)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__uARDeQU6tlhDvrSyWmbOoQ_12);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotasdfatsinstallsatsnimats2dot2dot4atslibatssystemdotnim_Init000();
	(*inner)();
#else
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotasdfatsinstallsatsnimats2dot2dot4atslibatssystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
NIM_BOOL oldNimErrFin4_;
NIM_BOOL oldNimErrFin3_;
NIM_BOOL oldNimErrFin48_;
NIM_BOOL oldNimErrFin47_;
NIM_BOOL* nimErr_;
	nimfr_("test1", "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/test1.nim");
nimErr_ = nimErrorFlag();
	nimlf_(5, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/test1.nim");	setStdIoUnbuffered__stdZsyncio_u528();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(7);	echoBinSafe(TM__uARDeQU6tlhDvrSyWmbOoQ_2, 1);
	{
		tyTuple__GGKW7Caq8ukhZanTky59bXg tmpTuple_1;
		nimln_(10);		fileTest__test1_u5 = TM__uARDeQU6tlhDvrSyWmbOoQ_5;
		nimln_(11);		fileOutput__test1_u6 = TM__uARDeQU6tlhDvrSyWmbOoQ_7;
		nimln_(12);		fileExpected__test1_u7 = TM__uARDeQU6tlhDvrSyWmbOoQ_9;
		nimln_(14);		addLangFrontmatter__OOZOOZsrcZnutilsZfrontpatch_u2(fileTest__test1_u5, fileOutput__test1_u6);
		if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
		nimln_(17);		tmpTuple_1 = openFilesToTest__helper_u4(fileTest__test1_u5);
		if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
		f_e__test1_u9 = tmpTuple_1.Field0;
		f_o__test1_u10 = tmpTuple_1.Field1;
		{
			NimStringV2 colontmpD_;
			NimStringV2 colontmpD__2;
			NI T7_;
			NI T8_;
			NimStringV2 T9_;
			tyArray__nHXaesL0DJZHyVS07ARPRA T10_;
			colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
			colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
			nimln_(22);			T7_ = (NI)0;
			T7_ = countLines__helper_u104(fileExpected__test1_u7);
			if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
			num_i__test1_u12 = T7_;
			nimln_(23);			T8_ = (NI)0;
			T8_ = countLines__helper_u104(fileOutput__test1_u6);
			if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
			num_o__test1_u13 = T8_;
			nimln_(24);			T9_.len = 0; T9_.p = NIM_NIL;
			colontmpD_ = dollar___systemZdollars_u14(num_i__test1_u12);
			if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
			colontmpD__2 = dollar___systemZdollars_u14(num_o__test1_u13);
			if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
			T9_ = rawNewString(colontmpD_.len + colontmpD__2.len + 40);
appendString((&T9_), TM__uARDeQU6tlhDvrSyWmbOoQ_11);
appendString((&T9_), colontmpD_);
appendString((&T9_), TM__uARDeQU6tlhDvrSyWmbOoQ_14);
appendString((&T9_), colontmpD__2);
			totalOfLines__test1_u14 = T9_;
			nimln_(25);			T10_[0] = totalOfLines__test1_u14;
			echoBinSafe(T10_, 1);
			nimln_(26);			{
				if (!!((num_i__test1_u12 == num_o__test1_u13))) goto LA13_;
				failedAssertImpl__stdZassertions_u234(TM__uARDeQU6tlhDvrSyWmbOoQ_16);
				if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
			}
LA13_: ;
			{
				NimStringV2 colontmpD__3;
				NIM_BOOL T17_;
				tyArray__Re75IspeoxXy2oCZHwcRrA T18_;
				colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
				nimln_(29);				T17_ = (NIM_BOOL)0;
				T17_ = allLinesEqual__helper_u113(fileOutput__test1_u6, fileExpected__test1_u7);
				if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
				equalLines__test1_u21 = T17_;
				nimln_(30);				T18_[0] = TM__uARDeQU6tlhDvrSyWmbOoQ_18;
				colontmpD__3 = nimBoolToStr(equalLines__test1_u21);
				T18_[1] = colontmpD__3;
				echoBinSafe(T18_, 2);
				nimln_(31);				{
					if (!!((equalLines__test1_u21 == NIM_TRUE))) goto LA21_;
					failedAssertImpl__stdZassertions_u234(TM__uARDeQU6tlhDvrSyWmbOoQ_20);
					if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
				}
LA21_: ;
				{
					LA16_:;
				}
				{
					nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");					if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
			}
			{
				NimStringV2 colontmpD__4;
				NIM_BOOL T27_;
				tyArray__Re75IspeoxXy2oCZHwcRrA T28_;
				colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
				nimlf_(34, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/test1.nim");				T27_ = (NIM_BOOL)0;
				T27_ = filesMatch__helper_u120(fileOutput__test1_u6, fileExpected__test1_u7);
				if (NIM_UNLIKELY(*nimErr_)) goto LA26_;
				byteToByte__test1_u28 = T27_;
				nimln_(35);				T28_[0] = TM__uARDeQU6tlhDvrSyWmbOoQ_22;
				colontmpD__4 = nimBoolToStr(byteToByte__test1_u28);
				T28_[1] = colontmpD__4;
				echoBinSafe(T28_, 2);
				nimln_(36);				{
					if (!!((byteToByte__test1_u28 == NIM_TRUE))) goto LA31_;
					failedAssertImpl__stdZassertions_u234(TM__uARDeQU6tlhDvrSyWmbOoQ_24);
					if (NIM_UNLIKELY(*nimErr_)) goto LA26_;
				}
LA31_: ;
				{
					LA26_:;
				}
				{
					nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");					if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
			}
			{
				LA6_:;
			}
			{
				if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
				if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
				if (totalOfLines__test1_u14.p && !(totalOfLines__test1_u14.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(totalOfLines__test1_u14.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
		}
		{
			LA4_:;
		}
		{
			oldNimErrFin4_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(19, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/test1.nim");			close__stdZsyncio_u268(f_o__test1_u10);
			if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
			*nimErr_ = oldNimErrFin4_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
		{
			LA3_:;
		}
		{
			oldNimErrFin3_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimln_(18);			close__stdZsyncio_u268(f_e__test1_u9);
			if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
			*nimErr_ = oldNimErrFin3_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
		{
			LA2_:;
		}
		{
			nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");			if (fileExpected__test1_u7.p && !(fileExpected__test1_u7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fileExpected__test1_u7.p);
}
			if (fileOutput__test1_u6.p && !(fileOutput__test1_u6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fileOutput__test1_u6.p);
}
			if (fileTest__test1_u5.p && !(fileTest__test1_u5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fileTest__test1_u5.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	nimlf_(38, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/test1.nim");	echoBinSafe(TM__uARDeQU6tlhDvrSyWmbOoQ_25, 1);
	{
		NimStringV2 T45_;
		NimStringV2 T46_;
		tyTuple__GGKW7Caq8ukhZanTky59bXg tmpTuple_2;
		nimln_(41);		fileTest__test1_u35 = TM__uARDeQU6tlhDvrSyWmbOoQ_28;
		nimln_(42);		T45_.len = 0; T45_.p = NIM_NIL;
		T45_ = rawNewString(fileTest__test1_u35.len + 48);
appendString((&T45_), TM__uARDeQU6tlhDvrSyWmbOoQ_30);
appendString((&T45_), fileTest__test1_u35);
appendString((&T45_), TM__uARDeQU6tlhDvrSyWmbOoQ_32);
		fileOutput__test1_u36 = T45_;
		nimln_(43);		T46_.len = 0; T46_.p = NIM_NIL;
		T46_ = rawNewString(fileTest__test1_u35.len + 48);
appendString((&T46_), TM__uARDeQU6tlhDvrSyWmbOoQ_34);
appendString((&T46_), fileTest__test1_u35);
appendString((&T46_), TM__uARDeQU6tlhDvrSyWmbOoQ_35);
		fileExpected__test1_u37 = T46_;
		nimln_(45);		addLangFrontmatter__OOZOOZsrcZnutilsZfrontpatch_u2(fileTest__test1_u35, fileOutput__test1_u36);
		if (NIM_UNLIKELY(*nimErr_)) goto LA44_;
		nimln_(47);		tmpTuple_2 = openFilesToTest__helper_u4(fileTest__test1_u35);
		if (NIM_UNLIKELY(*nimErr_)) goto LA44_;
		f_e__test1_u39 = tmpTuple_2.Field0;
		f_o__test1_u40 = tmpTuple_2.Field1;
		{
			NimStringV2 colontmpD__5;
			NimStringV2 colontmpD__6;
			NI T51_;
			NI T52_;
			NimStringV2 T53_;
			tyArray__nHXaesL0DJZHyVS07ARPRA T54_;
			colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
			colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
			nimln_(54);			T51_ = (NI)0;
			T51_ = countLines__helper_u104(fileExpected__test1_u37);
			if (NIM_UNLIKELY(*nimErr_)) goto LA50_;
			num_i__test1_u42 = T51_;
			nimln_(55);			T52_ = (NI)0;
			T52_ = countLines__helper_u104(fileOutput__test1_u36);
			if (NIM_UNLIKELY(*nimErr_)) goto LA50_;
			num_o__test1_u43 = T52_;
			nimln_(56);			T53_.len = 0; T53_.p = NIM_NIL;
			colontmpD__5 = dollar___systemZdollars_u14(num_i__test1_u42);
			if (NIM_UNLIKELY(*nimErr_)) goto LA50_;
			colontmpD__6 = dollar___systemZdollars_u14(num_o__test1_u43);
			if (NIM_UNLIKELY(*nimErr_)) goto LA50_;
			T53_ = rawNewString(colontmpD__5.len + colontmpD__6.len + 40);
appendString((&T53_), TM__uARDeQU6tlhDvrSyWmbOoQ_36);
appendString((&T53_), colontmpD__5);
appendString((&T53_), TM__uARDeQU6tlhDvrSyWmbOoQ_37);
appendString((&T53_), colontmpD__6);
			totalOfLines__test1_u44 = T53_;
			nimln_(57);			T54_[0] = totalOfLines__test1_u44;
			echoBinSafe(T54_, 1);
			nimln_(58);			{
				if (!!((num_i__test1_u42 == num_o__test1_u43))) goto LA57_;
				failedAssertImpl__stdZassertions_u234(TM__uARDeQU6tlhDvrSyWmbOoQ_39);
				if (NIM_UNLIKELY(*nimErr_)) goto LA50_;
			}
LA57_: ;
			{
				LA50_:;
			}
			{
				nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");				if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
				if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
				if (totalOfLines__test1_u44.p && !(totalOfLines__test1_u44.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(totalOfLines__test1_u44.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA48_;
		}
		{
			NimStringV2 colontmpD__7;
			NIM_BOOL T63_;
			tyArray__Re75IspeoxXy2oCZHwcRrA T64_;
			colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
			nimlf_(61, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/test1.nim");			T63_ = (NIM_BOOL)0;
			T63_ = allLinesEqual__helper_u113(fileOutput__test1_u36, fileExpected__test1_u37);
			if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
			equalLines__test1_u51 = T63_;
			nimln_(62);			T64_[0] = TM__uARDeQU6tlhDvrSyWmbOoQ_40;
			colontmpD__7 = nimBoolToStr(equalLines__test1_u51);
			T64_[1] = colontmpD__7;
			echoBinSafe(T64_, 2);
			nimln_(63);			{
				if (!!((equalLines__test1_u51 == NIM_TRUE))) goto LA67_;
				failedAssertImpl__stdZassertions_u234(TM__uARDeQU6tlhDvrSyWmbOoQ_42);
				if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
			}
LA67_: ;
			{
				LA62_:;
			}
			{
				nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");				if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA48_;
		}
		{
			NimStringV2 colontmpD__8;
			NIM_BOOL T73_;
			tyArray__Re75IspeoxXy2oCZHwcRrA T74_;
			colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
			nimlf_(66, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/test1.nim");			T73_ = (NIM_BOOL)0;
			T73_ = filesMatch__helper_u120(fileOutput__test1_u36, fileExpected__test1_u37);
			if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
			byteToByte__test1_u58 = T73_;
			nimln_(67);			T74_[0] = TM__uARDeQU6tlhDvrSyWmbOoQ_43;
			colontmpD__8 = nimBoolToStr(byteToByte__test1_u58);
			T74_[1] = colontmpD__8;
			echoBinSafe(T74_, 2);
			nimln_(68);			{
				if (!!((byteToByte__test1_u58 == NIM_TRUE))) goto LA77_;
				failedAssertImpl__stdZassertions_u234(TM__uARDeQU6tlhDvrSyWmbOoQ_45);
				if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
			}
LA77_: ;
			{
				LA72_:;
			}
			{
				nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");				if (colontmpD__8.p && !(colontmpD__8.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__8.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA48_;
		}
		{
			LA48_:;
		}
		{
			oldNimErrFin48_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(49, "/home/kang/PARA/Areas/Programming/Nim/Nutils/tests/testament/test1.nim");			close__stdZsyncio_u268(f_o__test1_u40);
			if (NIM_UNLIKELY(*nimErr_)) goto LA47_;
			*nimErr_ = oldNimErrFin48_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA47_;
		{
			LA47_:;
		}
		{
			oldNimErrFin47_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimln_(48);			close__stdZsyncio_u268(f_e__test1_u39);
			if (NIM_UNLIKELY(*nimErr_)) goto LA44_;
			*nimErr_ = oldNimErrFin47_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA44_;
		{
			LA44_:;
		}
		{
			nimlf_(394, "/home/kang/.asdf/installs/nim/2.2.4/lib/system.nim");			if (fileExpected__test1_u37.p && !(fileExpected__test1_u37.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fileExpected__test1_u37.p);
}
			if (fileOutput__test1_u36.p && !(fileOutput__test1_u36.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fileOutput__test1_u36.p);
}
			if (fileTest__test1_u35.p && !(fileTest__test1_u35.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fileTest__test1_u35.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

